// OutNYC curated catalog: Brooklyn (generated)
import type { Candidate } from '../types';

/** Restaurants + bars (kind: 'restaurant' | 'bar'). */
export const BROOKLYN_PLACES: Candidate[] = [
  // ── Williamsburg ──────────────────────────────────────────────
  {
    id: 'bk-peter-luger',
    name: 'Peter Luger Steak House',
    kind: 'restaurant',
    neighborhood: 'Williamsburg',
    priceTier: 4,
    durationMin: 120,
    lat: 40.7099,
    lng: -73.9622,
    address: '178 Broadway, Brooklyn, NY',
    bookingUrl: 'https://peterluger.com',
    description: 'Steakhouse: the 1887 porterhouse temple still running on dry-aged swagger.',
    tags: ['food'],
    cuisine: 'Steakhouse',
  },
  {
    id: 'bk-bamontes',
    name: 'Bamonte\'s',
    kind: 'restaurant',
    neighborhood: 'Williamsburg',
    priceTier: 2,
    durationMin: 90,
    lat: 40.7167,
    lng: -73.9497,
    address: '32 Withers St, Brooklyn, NY',
    description: 'Red-sauce Italian: a 1900 time capsule with tuxedoed waiters and killer clams oreganata.',
    tags: ['food'],
    cuisine: 'Italian',
  },
  {
    id: 'bk-l-industrie',
    name: 'L\'industrie Pizzeria',
    kind: 'restaurant',
    neighborhood: 'Williamsburg',
    priceTier: 1,
    durationMin: 30,
    lat: 40.7115,
    lng: -73.9583,
    address: '254 S 2nd St, Brooklyn, NY',
    description: 'Slice shop: burrata-topped squares with a permanent line down S 2nd St.',
    tags: ['food'],
    cuisine: 'Pizza',
  },
  {
    id: 'bk-birds-of-a-feather',
    name: 'Birds of a Feather',
    kind: 'restaurant',
    neighborhood: 'Williamsburg',
    priceTier: 2,
    durationMin: 90,
    lat: 40.7132,
    lng: -73.9613,
    address: '191 Grand St, Brooklyn, NY',
    description: 'Sichuan restaurant: tingly dry pots and chili chicken from the Cafe China team.',
    tags: ['food'],
    cuisine: 'Chinese',
  },
  {
    id: 'bk-shalom-japan',
    name: 'Shalom Japan',
    kind: 'restaurant',
    neighborhood: 'Williamsburg',
    priceTier: 3,
    durationMin: 90,
    lat: 40.7107,
    lng: -73.9576,
    address: '310 S 4th St, Brooklyn, NY',
    bookingUrl: 'https://www.shalomjapannyc.com',
    description: 'Japanese-Jewish mashup: matzo ball ramen and sake challah, playful and precise.',
    tags: ['food', 'brunch'],
    cuisine: 'Japanese',
  },
  {
    id: 'bk-diner',
    name: 'Diner',
    kind: 'restaurant',
    neighborhood: 'Williamsburg',
    priceTier: 3,
    durationMin: 90,
    lat: 40.7106,
    lng: -73.966,
    address: '85 Broadway, Brooklyn, NY',
    bookingUrl: 'https://dinernyc.com',
    description: 'New American: a 1927 dining car where the menu is scrawled on your paper tablecloth.',
    tags: ['food', 'brunch'],
    cuisine: 'American',
  },
  {
    id: 'bk-sunday-in-brooklyn',
    name: 'Sunday in Brooklyn',
    kind: 'restaurant',
    neighborhood: 'Williamsburg',
    priceTier: 2,
    durationMin: 75,
    lat: 40.7135,
    lng: -73.9655,
    address: '348 Wythe Ave, Brooklyn, NY',
    bookingUrl: 'https://www.sundayinbrooklyn.com',
    description: 'Brunch destination: malted pancakes with hazelnut praline worth the wait.',
    tags: ['food', 'brunch'],
    cuisine: 'American',
  },
  {
    id: 'bk-pies-n-thighs',
    name: 'Pies \'n\' Thighs',
    kind: 'restaurant',
    neighborhood: 'Williamsburg',
    priceTier: 2,
    durationMin: 75,
    lat: 40.7109,
    lng: -73.9617,
    address: '166 S 4th St, Brooklyn, NY',
    bookingUrl: 'https://piesnthighs.com',
    description: 'Southern comfort: fried-chicken biscuits and pie by the Williamsburg Bridge.',
    tags: ['food', 'brunch'],
    cuisine: 'Southern',
  },
  {
    id: 'bk-fette-sau',
    name: 'Fette Sau',
    kind: 'restaurant',
    neighborhood: 'Williamsburg',
    priceTier: 2,
    durationMin: 75,
    lat: 40.7146,
    lng: -73.9552,
    address: '354 Metropolitan Ave, Brooklyn, NY',
    bookingUrl: 'https://www.fettesaubbq.com',
    description: 'Barbecue: brisket by the pound on butcher paper in a converted garage.',
    tags: ['food'],
    cuisine: 'Southern',
  },
  {
    id: 'bk-bagelsmith',
    name: 'Bagelsmith',
    kind: 'restaurant',
    neighborhood: 'Williamsburg',
    priceTier: 1,
    durationMin: 30,
    lat: 40.714,
    lng: -73.9508,
    address: '566 Lorimer St, Brooklyn, NY',
    description: 'Bagel shop: hand-rolled bagels stacked high, open late for the Lorimer St crowd.',
    tags: ['food', 'late-night'],
    cuisine: 'Deli',
  },
  {
    id: 'bk-oddfellows',
    name: 'OddFellows Ice Cream Co.',
    kind: 'restaurant',
    neighborhood: 'Williamsburg',
    priceTier: 1,
    durationMin: 30,
    lat: 40.7146,
    lng: -73.9675,
    address: '40 River St, Brooklyn, NY',
    description: 'Ice cream parlor: small-batch oddball flavors like miso cherry at Domino Park.',
    tags: ['food'],
  },
  {
    id: 'bk-partners-coffee',
    name: 'Partners Coffee',
    kind: 'restaurant',
    neighborhood: 'Williamsburg',
    priceTier: 1,
    durationMin: 30,
    lat: 40.7175,
    lng: -73.96,
    address: '125 N 6th St, Brooklyn, NY',
    bookingUrl: 'https://www.partnerscoffee.com',
    description: 'Coffee roaster: the former Toby\'s Estate flagship, serious pour-overs.',
    tags: ['food', 'coffee'],
    cuisine: 'Coffee',
  },
  {
    id: 'bk-variety-coffee',
    name: 'Variety Coffee Roasters',
    kind: 'restaurant',
    neighborhood: 'Williamsburg',
    priceTier: 1,
    durationMin: 30,
    lat: 40.7147,
    lng: -73.9443,
    address: '368 Graham Ave, Brooklyn, NY',
    description: 'Coffee shop: no-fuss Graham Ave roaster with bottomless-feeling refills.',
    tags: ['food', 'coffee'],
    cuisine: 'Coffee',
  },
  {
    id: 'bk-maison-premiere',
    name: 'Maison Premiere',
    kind: 'bar',
    neighborhood: 'Williamsburg',
    priceTier: 3,
    durationMin: 90,
    lat: 40.7143,
    lng: -73.9614,
    address: '298 Bedford Ave, Brooklyn, NY',
    bookingUrl: 'https://maisonpremiere.com',
    description: 'Oyster & absinthe bar: New Orleans grandeur with a lush garden out back.',
    tags: ['bar', 'food'],
  },
  {
    id: 'bk-four-horsemen',
    name: 'The Four Horsemen',
    kind: 'bar',
    neighborhood: 'Williamsburg',
    priceTier: 3,
    durationMin: 90,
    lat: 40.7126,
    lng: -73.9585,
    address: '295 Grand St, Brooklyn, NY',
    bookingUrl: 'https://fourhorsemenbk.com',
    description: 'Natural wine bar: James Beard-winning list co-owned by LCD\'s James Murphy.',
    tags: ['bar', 'food'],
  },
  {
    id: 'bk-union-pool',
    name: 'Union Pool',
    kind: 'bar',
    neighborhood: 'Williamsburg',
    priceTier: 1,
    durationMin: 120,
    lat: 40.7174,
    lng: -73.9515,
    address: '484 Union Ave, Brooklyn, NY',
    bookingUrl: 'https://union-pool.com',
    description: 'Dive bar: taco truck, fire-pit courtyard, and late-night bands in a former pool supplier.',
    tags: ['bar', 'live music', 'late-night'],
  },
  {
    id: 'bk-radegast-hall',
    name: 'Radegast Hall & Biergarten',
    kind: 'bar',
    neighborhood: 'Williamsburg',
    priceTier: 2,
    durationMin: 90,
    lat: 40.7166,
    lng: -73.9614,
    address: '113 N 3rd St, Brooklyn, NY',
    bookingUrl: 'https://radegasthall.com',
    description: 'Beer hall: Austro-Hungarian biergarten with a retractable roof and live brass.',
    tags: ['bar', 'food', 'live music'],
  },
  {
    id: 'bk-berry-park',
    name: 'Berry Park',
    kind: 'bar',
    neighborhood: 'Williamsburg',
    priceTier: 2,
    durationMin: 90,
    lat: 40.7221,
    lng: -73.9556,
    address: '4 Berry St, Brooklyn, NY',
    description: 'Rooftop bar: beer hall downstairs, skyline roof deck upstairs by McCarren Park.',
    tags: ['bar', 'rooftop', 'food'],
  },
  {
    id: 'bk-bar-blondeau',
    name: 'Bar Blondeau',
    kind: 'bar',
    neighborhood: 'Williamsburg',
    priceTier: 3,
    durationMin: 90,
    lat: 40.7217,
    lng: -73.9582,
    address: '80 Wythe Ave, Brooklyn, NY',
    description: 'Rooftop wine bar: sixth-floor Wythe Hotel views with oysters and French leanings.',
    tags: ['bar', 'rooftop', 'food'],
  },
  {
    id: 'bk-other-half-domino',
    name: 'Other Half Brewing: Domino Park',
    kind: 'bar',
    neighborhood: 'Williamsburg',
    priceTier: 2,
    durationMin: 90,
    lat: 40.7146,
    lng: -73.9668,
    address: '34 River St, Brooklyn, NY',
    bookingUrl: 'https://otherhalfbrewing.com',
    description: 'Brewery taproom: hazy IPAs steps from Domino Park\'s waterfront lawn.',
    tags: ['bar', 'outdoors'],
  },
  {
    id: 'bk-metropolitan-bar',
    name: 'Metropolitan Bar',
    kind: 'bar',
    neighborhood: 'Williamsburg',
    priceTier: 1,
    durationMin: 120,
    lat: 40.7143,
    lng: -73.9507,
    address: '559 Lorimer St, Brooklyn, NY',
    description: 'Queer dive: beloved LGBTQ+ hangout with a backyard, pool table, and dance nights.',
    tags: ['bar', 'late-night'],
  },

  // ── Greenpoint ────────────────────────────────────────────────
  {
    id: 'bk-oxomoco',
    name: 'Oxomoco',
    kind: 'restaurant',
    neighborhood: 'Greenpoint',
    priceTier: 3,
    durationMin: 90,
    lat: 40.7301,
    lng: -73.9541,
    address: '128 Greenpoint Ave, Brooklyn, NY',
    bookingUrl: 'https://www.oxomoconyc.com',
    description: 'Wood-fired Mexican: Michelin-starred tacos, beet chorizo, and smoky mezcal.',
    tags: ['food', 'brunch'],
    cuisine: 'Mexican',
  },
  {
    id: 'bk-taqueria-ramirez',
    name: 'Taqueria Ramírez',
    kind: 'restaurant',
    neighborhood: 'Greenpoint',
    priceTier: 1,
    durationMin: 30,
    lat: 40.7289,
    lng: -73.9578,
    address: '94 Franklin St, Brooklyn, NY',
    description: 'Taqueria: CDMX-style suadero and longaniza straight off a blazing choricera.',
    tags: ['food'],
    cuisine: 'Mexican',
  },
  {
    id: 'bk-frankels',
    name: 'Frankel\'s Delicatessen & Appetizing',
    kind: 'restaurant',
    neighborhood: 'Greenpoint',
    priceTier: 1,
    durationMin: 45,
    lat: 40.7252,
    lng: -73.9512,
    address: '631 Manhattan Ave, Brooklyn, NY',
    bookingUrl: 'https://www.frankelsdelicatessen.com',
    description: 'Jewish deli: pastrami egg n\' cheese and hand-sliced lox, new-school appetizing.',
    tags: ['food', 'brunch'],
    cuisine: 'Deli',
  },
  {
    id: 'bk-glasserie',
    name: 'Glasserie',
    kind: 'restaurant',
    neighborhood: 'Greenpoint',
    priceTier: 3,
    durationMin: 90,
    lat: 40.7377,
    lng: -73.9533,
    address: '95 Commercial St, Brooklyn, NY',
    bookingUrl: 'https://www.glasserienyc.com',
    description: 'Middle Eastern: inventive Levantine plates in a former glassworks at Greenpoint\'s edge.',
    tags: ['food', 'brunch'],
    cuisine: 'Middle Eastern',
  },
  {
    id: 'bk-greenpoint-fish',
    name: 'Greenpoint Fish & Lobster Co.',
    kind: 'restaurant',
    neighborhood: 'Greenpoint',
    priceTier: 2,
    durationMin: 60,
    lat: 40.7241,
    lng: -73.9489,
    address: '114 Nassau Ave, Brooklyn, NY',
    bookingUrl: 'https://www.greenpointfish.com',
    description: 'Seafood counter: lobster rolls and a raw bar inside a working fish market.',
    tags: ['food'],
    cuisine: 'Seafood',
  },
  {
    id: 'bk-bernies',
    name: 'Bernie\'s',
    kind: 'restaurant',
    neighborhood: 'Greenpoint',
    priceTier: 2,
    durationMin: 90,
    lat: 40.7236,
    lng: -73.9438,
    address: '332 Driggs Ave, Brooklyn, NY',
    description: 'Retro American: red-checked tablecloths, chicken parm, and dirty martinis.',
    tags: ['food'],
    cuisine: 'American',
  },
  {
    id: 'bk-karczma',
    name: 'Karczma',
    kind: 'restaurant',
    neighborhood: 'Greenpoint',
    priceTier: 2,
    durationMin: 90,
    lat: 40.7302,
    lng: -73.9533,
    address: '136 Greenpoint Ave, Brooklyn, NY',
    description: 'Polish tavern: pierogi platters and grilled kielbasa served by staff in folk dress.',
    tags: ['food'],
  },
  {
    id: 'bk-christinas',
    name: 'Christina\'s',
    kind: 'restaurant',
    neighborhood: 'Greenpoint',
    priceTier: 1,
    durationMin: 60,
    lat: 40.7292,
    lng: -73.9539,
    address: '853 Manhattan Ave, Brooklyn, NY',
    description: 'Polish diner: cheap blintzes, borscht, and pierogi, a Manhattan Ave standby.',
    tags: ['food', 'brunch'],
  },
  {
    id: 'bk-cafe-grumpy',
    name: 'Café Grumpy',
    kind: 'restaurant',
    neighborhood: 'Greenpoint',
    priceTier: 1,
    durationMin: 30,
    lat: 40.7266,
    lng: -73.9499,
    address: '193 Meserole Ave, Brooklyn, NY',
    bookingUrl: 'https://cafegrumpy.com',
    description: 'Coffee shop: the original Greenpoint roastery-café that spawned the mini-chain.',
    tags: ['food', 'coffee'],
    cuisine: 'Coffee',
  },
  {
    id: 'bk-ovenly',
    name: 'Ovenly',
    kind: 'restaurant',
    neighborhood: 'Greenpoint',
    priceTier: 1,
    durationMin: 30,
    lat: 40.7305,
    lng: -73.9581,
    address: '31 Greenpoint Ave, Brooklyn, NY',
    bookingUrl: 'https://ovenly.com',
    description: 'Bakery: salted-chocolate-chip cookies and Brooklyn blackout cake near the water.',
    tags: ['food', 'coffee'],
    cuisine: 'Bakery',
  },
  {
    id: 'bk-achilles-heel',
    name: 'Achilles Heel',
    kind: 'bar',
    neighborhood: 'Greenpoint',
    priceTier: 2,
    durationMin: 90,
    lat: 40.7314,
    lng: -73.9601,
    address: '180 West St, Brooklyn, NY',
    description: 'Waterfront tavern: candlelit corner bar with natural wine and stiff drinks.',
    tags: ['bar', 'food'],
  },
  {
    id: 'bk-torst',
    name: 'Tørst',
    kind: 'bar',
    neighborhood: 'Greenpoint',
    priceTier: 2,
    durationMin: 90,
    lat: 40.7247,
    lng: -73.9509,
    address: '615 Manhattan Ave, Brooklyn, NY',
    description: 'Craft beer bar: a marble-and-oak temple with 21 meticulously kept taps.',
    tags: ['bar'],
  },
  {
    id: 'bk-ramona',
    name: 'Ramona',
    kind: 'bar',
    neighborhood: 'Greenpoint',
    priceTier: 2,
    durationMin: 90,
    lat: 40.7293,
    lng: -73.9583,
    address: '113 Franklin St, Brooklyn, NY',
    description: 'Cocktail bar: marble-and-fern room for well-made drinks and weekend DJs.',
    tags: ['bar', 'late-night'],
  },

  // ── Bushwick ──────────────────────────────────────────────────
  {
    id: 'bk-momo-sushi-shack',
    name: 'Momo Sushi Shack',
    kind: 'restaurant',
    neighborhood: 'Bushwick',
    priceTier: 2,
    durationMin: 90,
    lat: 40.7051,
    lng: -73.9337,
    address: '43 Bogart St, Brooklyn, NY',
    bookingUrl: 'https://www.momosushishack.com',
    description: 'Communal sushi: inventive rolls and sushi bombs in an industrial plywood den.',
    tags: ['food'],
    cuisine: 'Sushi',
  },
  {
    id: 'bk-ops',
    name: 'Ops',
    kind: 'restaurant',
    neighborhood: 'Bushwick',
    priceTier: 2,
    durationMin: 90,
    lat: 40.6999,
    lng: -73.9215,
    address: '346 Himrod St, Brooklyn, NY',
    description: 'Sourdough pizzeria: naturally leavened pies and natural wine in a tin-ceilinged room.',
    tags: ['food'],
    cuisine: 'Pizza',
  },
  {
    id: 'bk-los-hermanos',
    name: 'Tortilleria Mexicana Los Hermanos',
    kind: 'restaurant',
    neighborhood: 'Bushwick',
    priceTier: 1,
    durationMin: 45,
    lat: 40.7047,
    lng: -73.9222,
    address: '271 Starr St, Brooklyn, NY',
    description: 'Taqueria: tacos on tortillas pressed in the factory next door, cash and BYO.',
    tags: ['food'],
    cuisine: 'Mexican',
  },
  {
    id: 'bk-ichiran-bushwick',
    name: 'Ichiran Brooklyn',
    kind: 'restaurant',
    neighborhood: 'Bushwick',
    priceTier: 2,
    durationMin: 45,
    lat: 40.7075,
    lng: -73.9332,
    address: '374 Johnson Ave, Brooklyn, NY',
    bookingUrl: 'https://en.ichiran.com',
    description: 'Ramen bar: solo flavor-concentration booths for Japan\'s famous tonkotsu.',
    tags: ['food'],
    cuisine: 'Japanese',
  },
  {
    id: 'bk-mominette',
    name: 'Mominette',
    kind: 'restaurant',
    neighborhood: 'Bushwick',
    priceTier: 2,
    durationMin: 90,
    lat: 40.7032,
    lng: -73.9243,
    address: '221 Knickerbocker Ave, Brooklyn, NY',
    description: 'French bistro: steak frites, oysters, and a leafy backyard on Knickerbocker.',
    tags: ['food', 'brunch'],
    cuisine: 'French',
  },
  {
    id: 'bk-turks-inn',
    name: 'The Turk\'s Inn',
    kind: 'restaurant',
    neighborhood: 'Bushwick',
    priceTier: 3,
    durationMin: 90,
    lat: 40.7049,
    lng: -73.923,
    address: '234 Starr St, Brooklyn, NY',
    bookingUrl: 'https://www.theturksinn.com',
    description: 'Supper club: resurrected Wisconsin kitsch, kebabs, and a rooftop upstairs.',
    tags: ['food', 'rooftop'],
    cuisine: 'Middle Eastern',
  },
  {
    id: 'bk-limprimerie',
    name: 'L\'imprimerie',
    kind: 'restaurant',
    neighborhood: 'Bushwick',
    priceTier: 1,
    durationMin: 30,
    lat: 40.6999,
    lng: -73.912,
    address: '1524 Myrtle Ave, Brooklyn, NY',
    description: 'French bakery: croissants and jambon-beurre out of a former print shop.',
    tags: ['food', 'coffee'],
    cuisine: 'Bakery',
  },
  {
    id: 'bk-sey-coffee',
    name: 'SEY Coffee',
    kind: 'restaurant',
    neighborhood: 'Bushwick',
    priceTier: 1,
    durationMin: 30,
    lat: 40.7058,
    lng: -73.9333,
    address: '18 Grattan St, Brooklyn, NY',
    bookingUrl: 'https://www.seycoffee.com',
    description: 'Coffee shop: light-roast obsessives pulling shots in a skylit Grattan St loft.',
    tags: ['food', 'coffee'],
    cuisine: 'Coffee',
  },
  {
    id: 'bk-little-skips',
    name: 'Little Skips',
    kind: 'restaurant',
    neighborhood: 'Bushwick',
    priceTier: 1,
    durationMin: 45,
    lat: 40.6989,
    lng: -73.9318,
    address: '941 Willoughby Ave, Brooklyn, NY',
    description: 'Coffee shop: scrappy artist hangout with strong iced lattes and local art walls.',
    tags: ['food', 'coffee'],
    cuisine: 'Coffee',
  },
  {
    id: 'bk-kcbc',
    name: 'Kings County Brewers Collective (KCBC)',
    kind: 'bar',
    neighborhood: 'Bushwick',
    priceTier: 2,
    durationMin: 90,
    lat: 40.7066,
    lng: -73.9231,
    address: '381 Troutman St, Brooklyn, NY',
    bookingUrl: 'https://www.kcbcbeer.com',
    description: 'Brewery taproom: Bushwick\'s kaleidoscopic tap wall of IPAs, lagers, and sours.',
    tags: ['bar'],
  },
  {
    id: 'bk-the-narrows',
    name: 'The Narrows',
    kind: 'bar',
    neighborhood: 'Bushwick',
    priceTier: 2,
    durationMin: 90,
    lat: 40.7062,
    lng: -73.9337,
    address: '1037 Flushing Ave, Brooklyn, NY',
    description: 'Cocktail bar: narrow art-deco room with a back patio and serious negronis.',
    tags: ['bar', 'late-night'],
  },
  {
    id: 'bk-bossa-nova-civic-club',
    name: 'Bossa Nova Civic Club',
    kind: 'bar',
    neighborhood: 'Bushwick',
    priceTier: 2,
    durationMin: 150,
    lat: 40.6996,
    lng: -73.9223,
    address: '1271 Myrtle Ave, Brooklyn, NY',
    description: 'Dance bar: sweaty tropical bunker for house and techno heads, open very late.',
    tags: ['bar', 'late-night'],
  },
  {
    id: 'bk-happyfun-hideaway',
    name: 'Happyfun Hideaway',
    kind: 'bar',
    neighborhood: 'Bushwick',
    priceTier: 1,
    durationMin: 120,
    lat: 40.6999,
    lng: -73.925,
    address: '1211 Myrtle Ave, Brooklyn, NY',
    description: 'Queer dive: day-glo clubhouse with frozen drinks and a big backyard.',
    tags: ['bar', 'late-night'],
  },

  // ── DUMBO ─────────────────────────────────────────────────────
  {
    id: 'bk-julianas',
    name: 'Juliana\'s',
    kind: 'restaurant',
    neighborhood: 'DUMBO',
    priceTier: 2,
    durationMin: 60,
    lat: 40.7026,
    lng: -73.9934,
    address: '19 Old Fulton St, Brooklyn, NY',
    bookingUrl: 'https://julianaspizza.com',
    description: 'Coal-oven pizzeria: Patsy Grimaldi\'s return, thin-crust classics under the bridge.',
    tags: ['food'],
    cuisine: 'Pizza',
  },
  {
    id: 'bk-vinegar-hill-house',
    name: 'Vinegar Hill House',
    kind: 'restaurant',
    neighborhood: 'DUMBO',
    priceTier: 3,
    durationMin: 90,
    lat: 40.7033,
    lng: -73.9814,
    address: '72 Hudson Ave, Brooklyn, NY',
    bookingUrl: 'https://vinegarhillhouse.com',
    description: 'New American: wood-fired cast-iron chicken hidden on cobblestoned Hudson Ave.',
    tags: ['food', 'brunch'],
    cuisine: 'American',
  },
  {
    id: 'bk-cecconis',
    name: 'Cecconi\'s Dumbo',
    kind: 'restaurant',
    neighborhood: 'DUMBO',
    priceTier: 3,
    durationMin: 90,
    lat: 40.7036,
    lng: -73.991,
    address: '55 Water St, Brooklyn, NY',
    description: 'Italian: spritzes and handmade pasta with a full Manhattan-skyline terrace.',
    tags: ['food', 'brunch'],
    cuisine: 'Italian',
  },
  {
    id: 'bk-river-cafe',
    name: 'The River Café',
    kind: 'restaurant',
    neighborhood: 'DUMBO',
    priceTier: 4,
    durationMin: 120,
    lat: 40.7038,
    lng: -73.9945,
    address: '1 Water St, Brooklyn, NY',
    bookingUrl: 'https://therivercafe.com',
    description: 'Special-occasion American: jackets on, Brooklyn Bridge filling the window.',
    tags: ['food'],
    cuisine: 'American',
  },
  {
    id: 'bk-celestine',
    name: 'Celestine',
    kind: 'restaurant',
    neighborhood: 'DUMBO',
    priceTier: 3,
    durationMin: 90,
    lat: 40.704,
    lng: -73.9843,
    address: '1 John St, Brooklyn, NY',
    description: 'Eastern Mediterranean: inventive mezze with Manhattan Bridge views from John St.',
    tags: ['food', 'brunch'],
    cuisine: 'Mediterranean',
  },
  {
    id: 'bk-the-osprey',
    name: 'The Osprey',
    kind: 'restaurant',
    neighborhood: 'DUMBO',
    priceTier: 3,
    durationMin: 90,
    lat: 40.702,
    lng: -73.9958,
    address: '60 Furman St, Brooklyn, NY',
    description: 'All-day American: bright 1 Hotel dining room spilling toward the waterfront park.',
    tags: ['food', 'brunch'],
    cuisine: 'American',
  },
  {
    id: 'bk-pedros',
    name: 'Pedro\'s',
    kind: 'restaurant',
    neighborhood: 'DUMBO',
    priceTier: 1,
    durationMin: 60,
    lat: 40.7027,
    lng: -73.9866,
    address: '73 Jay St, Brooklyn, NY',
    description: 'Mexican cantina: cheap tacos and frozen margaritas, a holdout from gritty DUMBO.',
    tags: ['food'],
    cuisine: 'Mexican',
  },
  {
    id: 'bk-brooklyn-roasting',
    name: 'Brooklyn Roasting Company',
    kind: 'restaurant',
    neighborhood: 'DUMBO',
    priceTier: 1,
    durationMin: 30,
    lat: 40.7042,
    lng: -73.9857,
    address: '25 Jay St, Brooklyn, NY',
    bookingUrl: 'https://www.brooklynroasting.com',
    description: 'Coffee shop: burlap-sack roastery café that has fueled DUMBO for years.',
    tags: ['food', 'coffee'],
    cuisine: 'Coffee',
  },
  {
    id: 'bk-jacques-torres',
    name: 'Jacques Torres Chocolate',
    kind: 'restaurant',
    neighborhood: 'DUMBO',
    priceTier: 1,
    durationMin: 30,
    lat: 40.7033,
    lng: -73.9903,
    address: '66 Water St, Brooklyn, NY',
    bookingUrl: 'https://mrchocolate.com',
    description: 'Chocolate shop: Mr. Chocolate\'s original storefront, thick French hot cocoa.',
    tags: ['food'],
    cuisine: 'Bakery',
  },
  {
    id: 'bk-harriets-rooftop',
    name: 'Harriet\'s Rooftop',
    kind: 'bar',
    neighborhood: 'DUMBO',
    priceTier: 3,
    durationMin: 90,
    lat: 40.702,
    lng: -73.9957,
    address: '60 Furman St, Brooklyn, NY',
    description: 'Rooftop bar: 10th-floor cocktails staring straight at the Brooklyn Bridge.',
    tags: ['bar', 'rooftop'],
  },
  {
    id: 'bk-randolph-beer-dumbo',
    name: 'Randolph Beer DUMBO',
    kind: 'bar',
    neighborhood: 'DUMBO',
    priceTier: 2,
    durationMin: 90,
    lat: 40.7014,
    lng: -73.987,
    address: '82 Prospect St, Brooklyn, NY',
    description: 'Beer bar: self-pour tap wall, arcade games, and garage doors on Prospect St.',
    tags: ['bar', 'food'],
  },

  // ── Park Slope ────────────────────────────────────────────────
  {
    id: 'bk-al-di-la',
    name: 'al di là Trattoria',
    kind: 'restaurant',
    neighborhood: 'Park Slope',
    priceTier: 3,
    durationMin: 90,
    lat: 40.6774,
    lng: -73.981,
    address: '248 5th Ave, Brooklyn, NY',
    bookingUrl: 'https://aldilatrattoria.com',
    description: 'Venetian trattoria: malfatti and braised rabbit, a 5th Ave institution since 1998.',
    tags: ['food'],
    cuisine: 'Italian',
  },
  {
    id: 'bk-blue-ribbon-brooklyn',
    name: 'Blue Ribbon Brasserie Brooklyn',
    kind: 'restaurant',
    neighborhood: 'Park Slope',
    priceTier: 3,
    durationMin: 90,
    lat: 40.6766,
    lng: -73.9806,
    address: '280 5th Ave, Brooklyn, NY',
    description: 'American brasserie: oysters, fried chicken, and bone marrow served past midnight.',
    tags: ['food', 'late-night'],
    cuisine: 'American',
  },
  {
    id: 'bk-fonda',
    name: 'Fonda',
    kind: 'restaurant',
    neighborhood: 'Park Slope',
    priceTier: 2,
    durationMin: 90,
    lat: 40.6639,
    lng: -73.982,
    address: '434 7th Ave, Brooklyn, NY',
    description: 'Modern Mexican: chef Roberto Santibañez\'s enchiladas and proper margaritas.',
    tags: ['food', 'brunch'],
    cuisine: 'Mexican',
  },
  {
    id: 'bk-song',
    name: 'Song',
    kind: 'restaurant',
    neighborhood: 'Park Slope',
    priceTier: 1,
    durationMin: 60,
    lat: 40.6761,
    lng: -73.9803,
    address: '295 5th Ave, Brooklyn, NY',
    description: 'Thai: big cheap plates of noodles in a loud, mural-splashed room; cash only.',
    tags: ['food'],
    cuisine: 'Thai',
  },
  {
    id: 'bk-sushi-katsuei',
    name: 'Sushi Katsuei',
    kind: 'restaurant',
    neighborhood: 'Park Slope',
    priceTier: 3,
    durationMin: 90,
    lat: 40.6704,
    lng: -73.9782,
    address: '210 7th Ave, Brooklyn, NY',
    description: 'Sushi: omakase quality at neighborhood prices; book the counter.',
    tags: ['food'],
    cuisine: 'Sushi',
  },
  {
    id: 'bk-miriam',
    name: 'Miriam',
    kind: 'restaurant',
    neighborhood: 'Park Slope',
    priceTier: 2,
    durationMin: 75,
    lat: 40.6799,
    lng: -73.9779,
    address: '79 5th Ave, Brooklyn, NY',
    bookingUrl: 'https://www.miriamrestaurant.com',
    description: 'Israeli brunch spot: shakshuka and mimosas that pack 5th Ave every weekend.',
    tags: ['food', 'brunch'],
    cuisine: 'Middle Eastern',
  },
  {
    id: 'bk-luigis-pizza',
    name: 'Luigi\'s Pizza',
    kind: 'restaurant',
    neighborhood: 'Park Slope',
    priceTier: 1,
    durationMin: 30,
    lat: 40.6604,
    lng: -73.9887,
    address: '686 5th Ave, Brooklyn, NY',
    description: 'Slice joint: third-generation South Slope counter, fresh-mozz slice legend.',
    tags: ['food'],
    cuisine: 'Pizza',
  },
  {
    id: 'bk-bagel-hole',
    name: 'Bagel Hole',
    kind: 'restaurant',
    neighborhood: 'Park Slope',
    priceTier: 1,
    durationMin: 30,
    lat: 40.665,
    lng: -73.9812,
    address: '400 7th Ave, Brooklyn, NY',
    description: 'Bagel shop: small, dense, chewy old-school bagels; the purist\'s pick.',
    tags: ['food'],
    cuisine: 'Bakery',
  },
  {
    id: 'bk-cafe-regular-du-nord',
    name: 'Café Regular du Nord',
    kind: 'restaurant',
    neighborhood: 'Park Slope',
    priceTier: 1,
    durationMin: 30,
    lat: 40.6757,
    lng: -73.9748,
    address: '158A Berkeley Pl, Brooklyn, NY',
    description: 'Coffee shop: tiny Parisian-tiled nook for cortados just off 7th Ave.',
    tags: ['food', 'coffee'],
    cuisine: 'Coffee',
  },
  {
    id: 'bk-union-hall-bar',
    name: 'Union Hall',
    kind: 'bar',
    neighborhood: 'Park Slope',
    priceTier: 2,
    durationMin: 120,
    lat: 40.6771,
    lng: -73.979,
    address: '702 Union St, Brooklyn, NY',
    bookingUrl: 'https://www.unionhallny.com',
    description: 'Bar: indoor bocce courts, a fireplace library, and comedy in the basement.',
    tags: ['bar', 'comedy'],
  },
  {
    id: 'bk-freddys',
    name: 'Freddy\'s Bar',
    kind: 'bar',
    neighborhood: 'Park Slope',
    priceTier: 1,
    durationMin: 120,
    lat: 40.6621,
    lng: -73.9876,
    address: '627 5th Ave, Brooklyn, NY',
    bookingUrl: 'https://www.freddysbar.com',
    description: 'Dive bar: storied holdout with weird video art and free live music most nights.',
    tags: ['bar', 'live music', 'late-night'],
  },
  {
    id: 'bk-sea-witch',
    name: 'Sea Witch',
    kind: 'bar',
    neighborhood: 'Park Slope',
    priceTier: 1,
    durationMin: 90,
    lat: 40.6601,
    lng: -73.9891,
    address: '703 5th Ave, Brooklyn, NY',
    description: 'Nautical dive: fish tanks, a back-garden koi pond, and cheap drafts.',
    tags: ['bar', 'late-night'],
  },
];

/** Activities + fixed-time events (kind: 'activity' | 'event'). */
export const BROOKLYN_EVENTS: Candidate[] = [
  // ── Activities ────────────────────────────────────────────────
  {
    id: 'bk-domino-park',
    name: 'Domino Park',
    kind: 'activity',
    neighborhood: 'Williamsburg',
    durationMin: 60,
    lat: 40.7142,
    lng: -73.9679,
    address: '15 River St, Brooklyn, NY',
    bookingUrl: 'https://www.dominopark.com',
    description: 'Waterfront park: elevated catwalk past sugar-refinery relics, skyline sunsets.',
    tags: ['outdoors', 'walk'],
  },
  {
    id: 'bk-mccarren-park',
    name: 'McCarren Park',
    kind: 'activity',
    neighborhood: 'Williamsburg',
    durationMin: 60,
    lat: 40.7212,
    lng: -73.9515,
    address: '776 Lorimer St, Brooklyn, NY',
    description: 'City park: track loop, dog-watching, and a greenmarket where WB meets Greenpoint.',
    tags: ['outdoors', 'walk'],
  },
  {
    id: 'bk-marsha-p-johnson-park',
    name: 'Marsha P. Johnson State Park',
    kind: 'activity',
    neighborhood: 'Williamsburg',
    durationMin: 45,
    lat: 40.7212,
    lng: -73.9618,
    address: '90 Kent Ave, Brooklyn, NY',
    description: 'State park: open lawns and a rocky shoreline with the best free skyline view in WB.',
    tags: ['outdoors', 'walk'],
  },
  {
    id: 'bk-artists-and-fleas',
    name: 'Artists & Fleas Williamsburg',
    kind: 'activity',
    neighborhood: 'Williamsburg',
    durationMin: 60,
    lat: 40.7183,
    lng: -73.9611,
    address: '70 N 7th St, Brooklyn, NY',
    bookingUrl: 'https://artistsandfleas.com',
    description: 'Weekend market: indie makers, vintage racks, and vinyl crates under one roof.',
    tags: ['walk', 'art'],
  },
  {
    id: 'bk-city-reliquary',
    name: 'City Reliquary Museum',
    kind: 'activity',
    neighborhood: 'Williamsburg',
    priceTier: 1,
    durationMin: 45,
    lat: 40.714,
    lng: -73.9535,
    address: '370 Metropolitan Ave, Brooklyn, NY',
    bookingUrl: 'https://www.cityreliquary.org',
    description: 'Micro-museum: obsessive cases of NYC ephemera, from subway tokens to seltzer.',
    tags: ['art'],
  },
  {
    id: 'bk-mcgolrick-park',
    name: 'Monsignor McGolrick Park',
    kind: 'activity',
    neighborhood: 'Greenpoint',
    durationMin: 45,
    lat: 40.7243,
    lng: -73.9434,
    address: 'Nassau Ave & Russell St, Brooklyn, NY',
    description: 'Neighborhood park: colonnaded pavilion, old shade trees, Sunday farmers market.',
    tags: ['outdoors', 'walk'],
  },
  {
    id: 'bk-beacons-closet-greenpoint',
    name: 'Beacon\'s Closet Greenpoint',
    kind: 'activity',
    neighborhood: 'Greenpoint',
    durationMin: 60,
    lat: 40.7249,
    lng: -73.9522,
    address: '74 Guernsey St, Brooklyn, NY',
    bookingUrl: 'https://beaconscloset.com',
    description: 'Vintage megastore: the flagship secondhand trove; give it an hour minimum.',
    tags: ['walk'],
  },
  {
    id: 'bk-morgan-ave-murals',
    name: 'Morgan Avenue murals walk',
    kind: 'activity',
    neighborhood: 'Bushwick',
    durationMin: 60,
    lat: 40.706,
    lng: -73.9335,
    address: 'Morgan Ave & Grattan St, Brooklyn, NY',
    description: 'Street-art stroll: warehouse-district murals along Morgan, Bogart, and Grattan.',
    tags: ['art', 'walk', 'outdoors'],
  },
  {
    id: 'bk-maria-hernandez-park',
    name: 'Maria Hernandez Park',
    kind: 'activity',
    neighborhood: 'Bushwick',
    durationMin: 45,
    lat: 40.7034,
    lng: -73.9184,
    address: 'Knickerbocker Ave & Suydam St, Brooklyn, NY',
    description: 'City park: Bushwick\'s green heart, handball courts and coffee-cart laps.',
    tags: ['outdoors', 'walk'],
  },
  {
    id: 'bk-brooklyn-heights-promenade',
    name: 'Brooklyn Heights Promenade walk',
    kind: 'activity',
    neighborhood: 'DUMBO',
    durationMin: 60,
    lat: 40.6963,
    lng: -73.9967,
    address: 'Montague St & Pierrepont Pl, Brooklyn, NY',
    description: 'Skyline walk: the classic cantilevered promenade view of Lower Manhattan.',
    tags: ['outdoors', 'walk'],
  },
  {
    id: 'bk-washington-street-stroll',
    name: 'DUMBO Washington Street stroll',
    kind: 'activity',
    neighborhood: 'DUMBO',
    durationMin: 45,
    lat: 40.7025,
    lng: -73.9893,
    address: 'Washington St & Water St, Brooklyn, NY',
    description: 'Photo walk: the Manhattan Bridge framed between brick warehouses and cobblestones.',
    tags: ['walk', 'outdoors'],
  },
  {
    id: 'bk-brooklyn-museum',
    name: 'Brooklyn Museum',
    kind: 'activity',
    neighborhood: 'Park Slope',
    priceTier: 2,
    durationMin: 120,
    lat: 40.6712,
    lng: -73.9636,
    address: '200 Eastern Pkwy, Brooklyn, NY',
    bookingUrl: 'https://www.brooklynmuseum.org',
    description: 'Encyclopedic museum: Egyptian wing to blockbuster contemporary shows in a Beaux-Arts pile.',
    tags: ['art'],
  },
  {
    id: 'bk-brooklyn-botanic-garden',
    name: 'Brooklyn Botanic Garden',
    kind: 'activity',
    neighborhood: 'Park Slope',
    priceTier: 2,
    durationMin: 120,
    lat: 40.6688,
    lng: -73.9622,
    address: '990 Washington Ave, Brooklyn, NY',
    bookingUrl: 'https://www.bbg.org',
    description: 'Botanic garden: cherry esplanade, bonsai museum, 52 acres of engineered calm.',
    tags: ['outdoors', 'walk'],
  },
  {
    id: 'bk-prospect-park-long-meadow',
    name: 'Prospect Park: Long Meadow walk',
    kind: 'activity',
    neighborhood: 'Park Slope',
    durationMin: 90,
    lat: 40.6673,
    lng: -73.9702,
    address: 'Prospect Park West & Grand Army Plaza, Brooklyn, NY',
    bookingUrl: 'https://www.prospectpark.org',
    description: 'Park walk: nearly a mile of unbroken Olmsted meadow from Grand Army Plaza.',
    tags: ['outdoors', 'walk'],
  },
  {
    id: 'bk-prospect-park-audubon',
    name: 'Prospect Park: Audubon Center at the Boathouse',
    kind: 'activity',
    neighborhood: 'Park Slope',
    durationMin: 60,
    lat: 40.6606,
    lng: -73.9648,
    address: '101 East Dr, Brooklyn, NY',
    bookingUrl: 'https://www.prospectpark.org',
    description: 'Boathouse stop: Beaux-Arts terrace on the Lullwater, herons and turtles included.',
    tags: ['outdoors', 'walk'],
  },

  // ── Fixed-time events ─────────────────────────────────────────
  {
    id: 'bk-music-hall-of-williamsburg-show',
    name: 'Live show at Music Hall of Williamsburg',
    kind: 'event',
    neighborhood: 'Williamsburg',
    priceTier: 2,
    startTime: '20:00',
    endTime: '23:00',
    lat: 40.7192,
    lng: -73.9614,
    address: '66 N 6th St, Brooklyn, NY',
    bookingUrl: 'https://www.musichallofwilliamsburg.com',
    description: 'Concert: a 550-cap Bowery Presents room; catch indie acts before the big stages.',
    tags: ['live music', 'late-night'],
  },
  {
    id: 'bk-babys-all-right-show',
    name: 'Late show at Baby\'s All Right',
    kind: 'event',
    neighborhood: 'Williamsburg',
    priceTier: 2,
    startTime: '21:00',
    endTime: '23:30',
    lat: 40.7107,
    lng: -73.9631,
    address: '146 Broadway, Brooklyn, NY',
    bookingUrl: 'https://babysallright.com',
    description: 'Concert: scrappy tastemaker stage behind a bar-diner on Broadway.',
    tags: ['live music', 'late-night'],
  },
  {
    id: 'bk-national-sawdust-show',
    name: 'Evening program at National Sawdust',
    kind: 'event',
    neighborhood: 'Williamsburg',
    priceTier: 3,
    startTime: '19:00',
    endTime: '21:00',
    lat: 40.7191,
    lng: -73.9617,
    address: '80 N 6th St, Brooklyn, NY',
    bookingUrl: 'https://www.nationalsawdust.org',
    description: 'New-music hall: genre-bending premieres in a dazzling faceted black box.',
    tags: ['live music', 'art'],
  },
  {
    id: 'bk-nitehawk-screening',
    name: 'Dinner-and-a-movie at Nitehawk Cinema',
    kind: 'event',
    neighborhood: 'Williamsburg',
    priceTier: 2,
    startTime: '19:30',
    endTime: '21:45',
    lat: 40.7163,
    lng: -73.9622,
    address: '136 Metropolitan Ave, Brooklyn, NY',
    bookingUrl: 'https://nitehawkcinema.com',
    description: 'Dine-in cinema: first-run and repertory picks with cocktails brought to your seat.',
    tags: ['film', 'food'],
  },
  {
    id: 'bk-elsewhere-show',
    name: 'Night show at Elsewhere',
    kind: 'event',
    neighborhood: 'Bushwick',
    priceTier: 2,
    startTime: '20:00',
    endTime: '23:30',
    lat: 40.7093,
    lng: -73.9273,
    address: '599 Johnson Ave, Brooklyn, NY',
    bookingUrl: 'https://www.elsewherebrooklyn.com',
    description: 'Warehouse venue: multi-room indie and electronic complex with a rooftop stage.',
    tags: ['live music', 'late-night'],
  },
  {
    id: 'bk-sultan-room-show',
    name: 'Show at The Sultan Room',
    kind: 'event',
    neighborhood: 'Bushwick',
    priceTier: 2,
    startTime: '20:00',
    endTime: '23:00',
    lat: 40.7049,
    lng: -73.9229,
    address: '234 Starr St, Brooklyn, NY',
    bookingUrl: 'https://www.thesultanroom.com',
    description: 'Club stage: disco-ball supper-club venue attached to the Turk\'s Inn.',
    tags: ['live music', 'late-night'],
  },
  {
    id: 'bk-union-hall-comedy',
    name: 'Comedy in the basement at Union Hall',
    kind: 'event',
    neighborhood: 'Park Slope',
    priceTier: 1,
    startTime: '20:00',
    endTime: '21:30',
    lat: 40.6771,
    lng: -73.979,
    address: '702 Union St, Brooklyn, NY',
    bookingUrl: 'https://www.unionhallny.com',
    description: 'Stand-up: big-name drop-ins in the basement of a bocce bar.',
    tags: ['comedy'],
  },
  {
    id: 'bk-st-anns-warehouse-show',
    name: 'Theater at St. Ann\'s Warehouse',
    kind: 'event',
    neighborhood: 'DUMBO',
    priceTier: 3,
    startTime: '19:30',
    endTime: '21:30',
    lat: 40.7038,
    lng: -73.9927,
    address: '45 Water St, Brooklyn, NY',
    bookingUrl: 'https://stannswarehouse.org',
    description: 'Avant theater: international productions in a Civil War-era tobacco warehouse.',
    tags: ['art'],
  },
];
