// OutNYC curated catalog: Queens & citywide icons (generated)
import type { Candidate } from '../types';

/** Restaurants + bars (kind: 'restaurant' | 'bar'). */
export const QUEENS_PLACES: Candidate[] = [
  // --- Astoria: Greek ---
  {
    id: 'qc-tellys-taverna',
    name: "Telly's Taverna",
    kind: 'restaurant',
    neighborhood: 'Astoria',
    priceTier: 3,
    durationMin: 90,
    lat: 40.7752,
    lng: -73.9135,
    address: '28-13 23rd Ave, Astoria, NY 11105',
    description: 'Greek taverna: charcoal-grilled whole fish and a breezy backyard, an Astoria classic.',
    tags: ['food'],
    cuisine: 'Greek',
  },
  {
    id: 'qc-agnanti',
    name: 'Agnanti',
    kind: 'restaurant',
    neighborhood: 'Astoria',
    priceTier: 3,
    durationMin: 90,
    lat: 40.7758,
    lng: -73.9235,
    address: '19-06 Ditmars Blvd, Astoria, NY 11105',
    description: 'Greek taverna: Constantinople-style meze at the edge of Astoria Park.',
    tags: ['food'],
    cuisine: 'Greek',
  },
  {
    id: 'qc-gregorys-26-corner-taverna',
    name: "Gregory's 26 Corner Taverna",
    kind: 'restaurant',
    neighborhood: 'Astoria',
    priceTier: 2,
    durationMin: 90,
    lat: 40.7752,
    lng: -73.9148,
    address: '26-02 23rd Ave, Astoria, NY 11105',
    description: 'Greek taverna: no-frills grilled octopus and lemon potatoes like a yiayia makes.',
    tags: ['food'],
    cuisine: 'Greek',
  },
  {
    id: 'qc-elias-corner',
    name: 'Elias Corner',
    kind: 'restaurant',
    neighborhood: 'Astoria',
    priceTier: 3,
    durationMin: 90,
    lat: 40.774,
    lng: -73.9133,
    address: '24-02 31st St, Astoria, NY 11102',
    description: 'Greek seafood: cash-only corner spot where you pick your fish from the ice case.',
    tags: ['food'],
    cuisine: 'Greek',
  },
  {
    id: 'qc-bz-grill',
    name: 'BZ Grill',
    kind: 'restaurant',
    neighborhood: 'Astoria',
    priceTier: 1,
    durationMin: 45,
    lat: 40.7708,
    lng: -73.922,
    address: '27-02 Astoria Blvd, Astoria, NY 11102',
    description: 'Gyro counter: crackly hand-stacked pork gyros that top NYC best-of lists.',
    tags: ['food'],
    cuisine: 'Greek',
  },
  // --- Astoria: Middle Eastern (Little Egypt) ---
  {
    id: 'qc-kabab-cafe',
    name: 'Kabab Cafe',
    kind: 'restaurant',
    neighborhood: 'Astoria',
    priceTier: 2,
    durationMin: 90,
    lat: 40.7714,
    lng: -73.9105,
    address: '25-12 Steinway St, Astoria, NY 11103',
    description: 'Egyptian den: tiny Steinway legend where chef Ali improvises meze tableside.',
    tags: ['food'],
    cuisine: 'Middle Eastern',
  },
  {
    id: 'qc-mombar',
    name: 'Mombar',
    kind: 'restaurant',
    neighborhood: 'Astoria',
    priceTier: 2,
    durationMin: 90,
    lat: 40.7711,
    lng: -73.9106,
    address: '25-22 Steinway St, Astoria, NY 11103',
    description: 'Egyptian dining room: hand-built mosaic interior and slow-cooked duck on Steinway.',
    tags: ['food'],
    cuisine: 'Middle Eastern',
  },
  // --- Astoria: Mexican ---
  {
    id: 'qc-de-mole-astoria',
    name: 'De Mole Astoria',
    kind: 'restaurant',
    neighborhood: 'Astoria',
    priceTier: 2,
    durationMin: 75,
    lat: 40.7612,
    lng: -73.9102,
    address: '42-20 30th Ave, Astoria, NY 11103',
    description: 'Mexican spot: homey enchiladas and mole in a cozy corner room, gentle prices.',
    tags: ['food'],
    cuisine: 'Mexican',
  },
  {
    id: 'qc-chela-garnacha',
    name: 'Chela & Garnacha',
    kind: 'restaurant',
    neighborhood: 'Astoria',
    priceTier: 2,
    durationMin: 75,
    lat: 40.7558,
    lng: -73.9276,
    address: '33-09 36th Ave, Astoria, NY 11106',
    description: 'Mexican taqueria: al pastor tacos and micheladas in a snug 36th Ave storefront.',
    tags: ['food'],
    cuisine: 'Mexican',
  },
  // --- Astoria: Thai, pizza, diner ---
  {
    id: 'qc-pye-boat-noodle',
    name: 'Pye Boat Noodle',
    kind: 'restaurant',
    neighborhood: 'Astoria',
    priceTier: 2,
    durationMin: 75,
    lat: 40.7599,
    lng: -73.9195,
    address: '35-13 Broadway, Astoria, NY 11106',
    description: 'Thai noodle house: dark, beefy boat noodles and papaya salad, Bangkok-style.',
    tags: ['food'],
    cuisine: 'Thai',
  },
  {
    id: 'qc-milkflower',
    name: 'Milkflower',
    kind: 'restaurant',
    neighborhood: 'Astoria',
    priceTier: 2,
    durationMin: 90,
    lat: 40.763,
    lng: -73.9202,
    address: '34-12 31st Ave, Astoria, NY 11106',
    description: 'Pizzeria: blistered wood-fired pies and natural wine in a rustic 31st Ave room.',
    tags: ['food'],
    cuisine: 'Pizza',
  },
  {
    id: 'qc-sanfords',
    name: 'Sanfords Restaurant',
    kind: 'restaurant',
    neighborhood: 'Astoria',
    priceTier: 2,
    durationMin: 75,
    lat: 40.7615,
    lng: -73.9245,
    address: '30-13 Broadway, Astoria, NY 11106',
    description: 'All-day diner: polished comfort food and cocktails very late; an Astoria institution.',
    tags: ['food', 'brunch', 'late-night'],
    cuisine: 'American',
  },
  // --- Astoria: bakeries + coffee ---
  {
    id: 'qc-la-guli-pastry',
    name: 'La Guli Pastry Shop',
    kind: 'restaurant',
    neighborhood: 'Astoria',
    priceTier: 1,
    durationMin: 30,
    lat: 40.7754,
    lng: -73.9135,
    address: '29-15 Ditmars Blvd, Astoria, NY 11105',
    description: 'Italian pastry shop: cannoli and lobster tails on Ditmars since 1937.',
    tags: ['food'],
    cuisine: 'Bakery',
  },
  {
    id: 'qc-artopolis-bakery',
    name: 'Artopolis Bakery',
    kind: 'restaurant',
    neighborhood: 'Astoria',
    priceTier: 1,
    durationMin: 30,
    lat: 40.7745,
    lng: -73.913,
    address: '23-18 31st St, Astoria, NY 11105',
    description: 'Greek bakery: galaktoboureko, koulourakia and strong coffee in Agora Plaza.',
    tags: ['food'],
    cuisine: 'Bakery',
  },
  {
    id: 'qc-marthas-country-bakery',
    name: "Martha's Country Bakery",
    kind: 'restaurant',
    neighborhood: 'Astoria',
    priceTier: 1,
    durationMin: 45,
    lat: 40.7742,
    lng: -73.907,
    address: '36-21 Ditmars Blvd, Astoria, NY 11105',
    bookingUrl: 'https://www.marthasbakery.com',
    description: 'Bakery cafe: towering cakes, pies and cheesecake for a Ditmars sugar stop.',
    tags: ['food'],
    cuisine: 'Bakery',
  },
  {
    id: 'qc-kinship-coffee',
    name: 'Kinship Coffee Cooperative',
    kind: 'restaurant',
    neighborhood: 'Astoria',
    priceTier: 1,
    durationMin: 45,
    lat: 40.7597,
    lng: -73.9166,
    address: '32-30 Steinway St, Astoria, NY 11103',
    description: 'Coffee shop: worker-owned Astoria cafe with solid espresso and roomy tables.',
    tags: ['food', 'coffee'],
    cuisine: 'Coffee',
  },
  {
    id: 'qc-astoria-seafood',
    name: 'Astoria Seafood',
    kind: 'restaurant',
    neighborhood: 'Long Island City',
    priceTier: 2,
    durationMin: 90,
    lat: 40.755,
    lng: -73.929,
    address: '37-10 33rd St, Long Island City, NY 11101',
    description: 'Fish market grill: pick your seafood from the ice and they cook it; chaotic, cheap, fun.',
    tags: ['food'],
    cuisine: 'Seafood',
  },
  // --- Long Island City: restaurants ---
  {
    id: 'qc-casa-enrique',
    name: 'Casa Enrique',
    kind: 'restaurant',
    neighborhood: 'Long Island City',
    priceTier: 3,
    durationMin: 90,
    lat: 40.7416,
    lng: -73.9527,
    address: '5-48 49th Ave, Long Island City, NY 11101',
    description: 'Mexican: Michelin-starred Chiapas cooking, lamb barbacoa and killer margaritas.',
    tags: ['food'],
    cuisine: 'Mexican',
  },
  {
    id: 'qc-jora',
    name: 'Jora',
    kind: 'restaurant',
    neighborhood: 'Long Island City',
    priceTier: 3,
    durationMin: 90,
    lat: 40.7443,
    lng: -73.9536,
    address: '47-46 11th St, Long Island City, NY 11101',
    description: 'Peruvian: lomo saltado, ceviche and pisco sours in a spacious LIC room.',
    tags: ['food', 'brunch'],
    cuisine: 'Peruvian',
  },
  {
    id: 'qc-manettas',
    name: "Manetta's Ristorante",
    kind: 'restaurant',
    neighborhood: 'Long Island City',
    priceTier: 2,
    durationMin: 90,
    lat: 40.7434,
    lng: -73.9512,
    address: '10-76 Jackson Ave, Long Island City, NY 11101',
    description: 'Italian: wood-fired pies and old-school red sauce, a family-run LIC standby.',
    tags: ['food'],
    cuisine: 'Italian',
  },
  {
    id: 'qc-sweetleaf-lic',
    name: 'Sweetleaf Coffee Roasters',
    kind: 'restaurant',
    neighborhood: 'Long Island City',
    priceTier: 1,
    durationMin: 45,
    lat: 40.7431,
    lng: -73.9515,
    address: '10-93 Jackson Ave, Long Island City, NY 11101',
    description: 'Coffee bar: LIC roaster pulling serious espresso in a vintage Jackson Ave nook.',
    tags: ['food', 'coffee'],
    cuisine: 'Coffee',
  },
  // --- Bars: Long Island City ---
  {
    id: 'qc-dutch-kills',
    name: 'Dutch Kills',
    kind: 'bar',
    neighborhood: 'Long Island City',
    priceTier: 2,
    durationMin: 90,
    lat: 40.7497,
    lng: -73.9397,
    address: '27-24 Jackson Ave, Long Island City, NY 11101',
    bookingUrl: 'https://dutchkillsbar.com',
    description: 'Cocktail bar: hand-cut ice and classic cocktails in a wood-boothed LIC saloon.',
    tags: ['bar', 'late-night'],
  },
  {
    id: 'qc-fifth-hammer-brewing',
    name: 'Fifth Hammer Brewing',
    kind: 'bar',
    neighborhood: 'Long Island City',
    priceTier: 2,
    durationMin: 90,
    lat: 40.7472,
    lng: -73.9487,
    address: '10-28 46th Ave, Long Island City, NY 11101',
    bookingUrl: 'https://fifthhammerbrewing.com',
    description: 'Brewery taproom: inventive IPAs and sours a short walk from the LIC waterfront.',
    tags: ['bar'],
  },
  {
    id: 'qc-rockaway-brewing',
    name: 'Rockaway Brewing Company',
    kind: 'bar',
    neighborhood: 'Long Island City',
    priceTier: 2,
    durationMin: 90,
    lat: 40.7469,
    lng: -73.9552,
    address: '46-01 5th St, Long Island City, NY 11101',
    bookingUrl: 'https://rockawaybrewco.com',
    description: 'Brewery taproom: easy-drinking beers and food pop-ups in an LIC garage space.',
    tags: ['bar'],
  },
  {
    id: 'qc-bierocracy',
    name: 'Bierocracy',
    kind: 'bar',
    neighborhood: 'Long Island City',
    priceTier: 2,
    durationMin: 90,
    lat: 40.744,
    lng: -73.9497,
    address: '12-23 Jackson Ave, Long Island City, NY 11101',
    description: 'Beer hall: big communal tables and European lagers by the half-liter.',
    tags: ['bar', 'food'],
  },
  // --- Bars: Astoria ---
  {
    id: 'qc-the-bonnie',
    name: 'The Bonnie',
    kind: 'bar',
    neighborhood: 'Astoria',
    priceTier: 2,
    durationMin: 90,
    lat: 40.7748,
    lng: -73.9126,
    address: '29-12 23rd Ave, Astoria, NY 11105',
    description: 'Bar: craft cocktails, a big garden and solid bar food off the Ditmars strip.',
    tags: ['bar', 'food', 'brunch'],
  },
  {
    id: 'qc-the-last-word',
    name: 'The Last Word',
    kind: 'bar',
    neighborhood: 'Astoria',
    priceTier: 3,
    durationMin: 90,
    lat: 40.7749,
    lng: -73.9105,
    address: '31-30 Ditmars Blvd, Astoria, NY 11105',
    description: 'Speakeasy: dim, bookshelf-door cocktail den mixing serious drinks till late.',
    tags: ['bar', 'late-night'],
  },
  {
    id: 'qc-sunswick-3535',
    name: 'Sunswick 35/35',
    kind: 'bar',
    neighborhood: 'Astoria',
    priceTier: 2,
    durationMin: 90,
    lat: 40.757,
    lng: -73.925,
    address: '35-02 35th St, Astoria, NY 11106',
    description: 'Beer bar: deep craft tap list and a relaxed corner-pub vibe near Kaufman Astoria.',
    tags: ['bar'],
  },
];

/** Activities + fixed-time events (kind: 'activity' | 'event'). */
export const QUEENS_CITYWIDE_EVENTS: Candidate[] = [
  // --- Astoria / LIC activities ---
  {
    id: 'qc-socrates-sculpture-park',
    name: 'Socrates Sculpture Park',
    kind: 'activity',
    neighborhood: 'Astoria',
    priceTier: 1,
    durationMin: 90,
    lat: 40.7686,
    lng: -73.9364,
    address: '32-01 Vernon Blvd, Queens, NY 11106',
    bookingUrl: 'https://socratessculpturepark.org',
    description: 'Sculpture park: free riverside art field with skyline views, made by artists.',
    tags: ['art', 'outdoors'],
  },
  {
    id: 'qc-noguchi-museum',
    name: 'The Noguchi Museum',
    kind: 'activity',
    neighborhood: 'Astoria',
    priceTier: 2,
    durationMin: 90,
    lat: 40.7669,
    lng: -73.9377,
    address: '9-01 33rd Rd, Queens, NY 11106',
    bookingUrl: 'https://www.noguchi.org',
    description: "Museum: Isamu Noguchi's serene stone sculptures around an indoor-outdoor garden.",
    tags: ['art'],
  },
  {
    id: 'qc-gantry-plaza-state-park',
    name: 'Gantry Plaza State Park',
    kind: 'activity',
    neighborhood: 'Long Island City',
    priceTier: 1,
    durationMin: 60,
    lat: 40.7462,
    lng: -73.958,
    address: '4-09 47th Rd, Long Island City, NY 11101',
    description: 'Waterfront park: restored gantries, piers and the Pepsi-Cola sign facing midtown.',
    tags: ['outdoors', 'walk'],
  },
  {
    id: 'qc-moma-ps1',
    name: 'MoMA PS1',
    kind: 'activity',
    neighborhood: 'Long Island City',
    priceTier: 2,
    durationMin: 120,
    lat: 40.7456,
    lng: -73.947,
    address: '22-25 Jackson Ave, Long Island City, NY 11101',
    bookingUrl: 'https://www.momaps1.org',
    description: 'Contemporary art museum: edgy rotating shows in a converted LIC schoolhouse.',
    tags: ['art'],
  },
  {
    id: 'qc-astoria-park-track',
    name: 'Astoria Park & Track',
    kind: 'activity',
    neighborhood: 'Astoria',
    priceTier: 1,
    durationMin: 90,
    lat: 40.7785,
    lng: -73.9228,
    address: '19th St & 23rd Dr, Astoria, NY 11105',
    bookingUrl: 'https://www.nycgovparks.org/parks/astoria-park',
    description: 'Riverside park: run the track under Hell Gate Bridge, swim the giant summer pool.',
    tags: ['outdoors', 'walk'],
  },
  {
    id: 'qc-hunters-point-south-park',
    name: 'Hunters Point South Park',
    kind: 'activity',
    neighborhood: 'Long Island City',
    priceTier: 1,
    durationMin: 60,
    lat: 40.7424,
    lng: -73.96,
    address: 'Center Blvd & 51st Ave, Long Island City, NY 11101',
    description: 'Waterfront park: grassy point with the best straight-on Manhattan skyline panorama.',
    tags: ['outdoors', 'walk'],
  },
  {
    id: 'qc-culture-lab-lic',
    name: 'Culture Lab LIC',
    kind: 'activity',
    neighborhood: 'Long Island City',
    priceTier: 1,
    durationMin: 75,
    lat: 40.7475,
    lng: -73.9547,
    address: '5-25 46th Ave, Long Island City, NY 11101',
    bookingUrl: 'https://www.culturelablic.org',
    description: 'Arts center: free galleries plus an outdoor stage with weekend shows near Gantry.',
    tags: ['art', 'live music'],
  },
  {
    id: 'qc-welling-court-murals',
    name: 'Welling Court Mural Project',
    kind: 'activity',
    neighborhood: 'Astoria',
    priceTier: 1,
    durationMin: 60,
    lat: 40.7702,
    lng: -73.9316,
    address: 'Welling Ct & 30th Ave, Astoria, NY 11102',
    description: 'Street-art walk: 150+ murals wrapping a few blocks near the Astoria waterfront.',
    tags: ['art', 'walk', 'outdoors'],
  },
  {
    id: 'qc-queensboro-bridge-walk',
    name: 'Queensboro Bridge Walk',
    kind: 'activity',
    neighborhood: 'Long Island City',
    priceTier: 1,
    durationMin: 75,
    lat: 40.7513,
    lng: -73.9407,
    address: 'Queens Plaza North & Crescent St, Long Island City, NY 11101',
    description: 'Bridge walk: stroll the 1909 span from Queens Plaza for East River and skyline views.',
    tags: ['walk', 'outdoors'],
  },
  // --- Citywide / floating (no neighborhood) ---
  {
    id: 'qc-governors-island-day',
    name: 'Governors Island Day Trip',
    kind: 'activity',
    priceTier: 1,
    durationMin: 300,
    lat: 40.701,
    lng: -74.0116,
    address: 'Battery Maritime Building, 10 South St, New York, NY 10004',
    bookingUrl: 'https://www.govisland.com',
    description: 'Island day trip: quick ferry to car-free hills, hammocks and harbor views; rent bikes.',
    tags: ['outdoors', 'walk'],
  },
  {
    id: 'qc-roosevelt-island-tram-loop',
    name: 'Lighthouse loop at Roosevelt Island',
    kind: 'activity',
    priceTier: 1,
    durationMin: 150,
    lat: 40.7614,
    lng: -73.9641,
    address: 'Tram Plaza, E 59th St & 2nd Ave, New York, NY 10022',
    bookingUrl: 'https://rioc.ny.gov',
    description: 'Tram ride: glide over the East River, then loop to the lighthouse and Four Freedoms Park.',
    tags: ['outdoors', 'walk'],
  },
  {
    id: 'qc-rockaway-beach-day',
    name: 'Rockaway Beach + Boardwalk',
    kind: 'activity',
    priceTier: 1,
    durationMin: 300,
    lat: 40.5837,
    lng: -73.8163,
    address: 'Beach 97th St & Shore Front Pkwy, Rockaway Park, NY 11694',
    description: 'Beach day: A-train surf beach with boardwalk tacos at the 97th St concessions.',
    tags: ['outdoors'],
    months: [6, 7, 8, 9], // A-train beach season
  },
  {
    id: 'qc-hudson-greenway-bike',
    name: 'Hudson River Greenway Bike Ride',
    kind: 'activity',
    priceTier: 1,
    durationMin: 120,
    lat: 40.7635,
    lng: -74.0,
    address: 'Pier 84, W 44th St & 12th Ave, New York, NY 10036',
    description: 'Bike ride: car-free riverfront path from the Battery to the GWB; grab a Citi Bike.',
    tags: ['outdoors'],
  },
  {
    id: 'qc-manhattan-brooklyn-bridge-loop',
    name: 'Manhattan Bridge to Brooklyn Bridge Loop',
    kind: 'activity',
    priceTier: 1,
    durationMin: 150,
    lat: 40.7158,
    lng: -73.9945,
    address: 'Manhattan Bridge entrance, Canal St & Bowery, New York, NY 10002',
    description: 'Bridge loop walk: cross the Manhattan Bridge, wander Dumbo, return over the Brooklyn Bridge.',
    tags: ['walk', 'outdoors'],
  },
  {
    id: 'qc-nyc-ferry-east-river',
    name: 'NYC Ferry East River Route',
    kind: 'activity',
    priceTier: 1,
    durationMin: 60,
    lat: 40.7031,
    lng: -74.0055,
    address: 'Pier 11/Wall St, New York, NY 10005',
    bookingUrl: 'https://www.ferry.nyc',
    description: 'Ferry ride: cheap skyline cruise up the East River from Wall St to Astoria, drinks on board.',
    tags: ['outdoors'],
  },
  {
    id: 'qc-downtown-boathouse-kayak',
    name: 'Free Kayaking at Downtown Boathouse',
    kind: 'activity',
    priceTier: 1,
    durationMin: 60,
    lat: 40.7203,
    lng: -74.0129,
    address: 'Pier 26, Hudson River Park, New York, NY 10013',
    bookingUrl: 'https://downtownboathouse.org',
    description: 'Free kayaking: volunteer-run walk-up paddling in a protected Hudson embayment.',
    tags: ['outdoors'],
    months: [5, 6, 7, 8, 9, 10], // free kayaking runs mid-May to mid-Oct
  },
  {
    id: 'qc-chelsea-piers-driving-range',
    name: 'Chelsea Piers Driving Range',
    kind: 'activity',
    priceTier: 2,
    durationMin: 90,
    lat: 40.7457,
    lng: -74.009,
    address: 'Pier 59, Chelsea Piers, New York, NY 10011',
    bookingUrl: 'https://www.chelseapiers.com/golf/',
    description: 'Driving range: hit balls toward the Hudson from four stacked tiers at Pier 59.',
    tags: ['outdoors'],
  },
  {
    id: 'qc-circle-line-harbor-cruise',
    name: 'Circle Line Harbor Cruise',
    kind: 'activity',
    priceTier: 3,
    durationMin: 150,
    lat: 40.7627,
    lng: -74.0,
    address: 'Pier 83, W 42nd St & 12th Ave, New York, NY 10036',
    bookingUrl: 'https://www.circleline.com',
    description: 'Harbor cruise: classic boat loop past the Statue of Liberty and under the bridges.',
    tags: ['outdoors'],
  },
  // --- Fixed-time events: Queens ---
  {
    id: 'qc-qed-comedy-night',
    name: 'Comedy Night at QED Astoria',
    kind: 'event',
    neighborhood: 'Astoria',
    priceTier: 1,
    startTime: '19:30',
    endTime: '21:00',
    lat: 40.7756,
    lng: -73.9127,
    address: '27-16 23rd Ave, Astoria, NY 11105',
    bookingUrl: 'https://qedastoria.com',
    description: "Comedy night: indie stand-up showcases in Astoria's scrappy 40-seat clubhouse.",
    tags: ['comedy'],
  },
  {
    id: 'qc-lic-bar-live-music',
    name: 'Live Music at LIC Bar',
    kind: 'event',
    neighborhood: 'Long Island City',
    priceTier: 1,
    startTime: '20:00',
    endTime: '22:00',
    lat: 40.7477,
    lng: -73.9537,
    address: '45-58 Vernon Blvd, Long Island City, NY 11101',
    description: 'Live music: free Americana and jazz sessions in a tin-ceilinged 1900s barroom.',
    tags: ['live music', 'bar'],
  },
  {
    id: 'qc-socrates-outdoor-cinema',
    name: 'Outdoor Cinema at Socrates Sculpture Park',
    kind: 'event',
    neighborhood: 'Astoria',
    priceTier: 1,
    startTime: '19:30',
    endTime: '21:30',
    lat: 40.7686,
    lng: -73.9364,
    address: '32-01 Vernon Blvd, Queens, NY 11106',
    bookingUrl: 'https://socratessculpturepark.org',
    description: 'Outdoor movie: free summer film under the skyline in the sculpture park; bring a blanket.',
    tags: ['film', 'outdoors'],
    months: [7, 8], // free outdoor film series is a summer program
  },
  // --- Fixed-time events: stadium nights (floating) ---
  {
    id: 'qc-mets-game-citi-field',
    name: 'Mets Game at Citi Field',
    kind: 'event',
    priceTier: 2,
    startTime: '19:10',
    endTime: '22:10',
    lat: 40.7571,
    lng: -73.8458,
    address: '41 Seaver Way, Queens, NY 11368',
    bookingUrl: 'https://www.mlb.com/mets',
    description: 'Ballgame: night baseball at Citi Field with a Shake Shack stop behind center field.',
    tags: ['outdoors'],
    months: [4, 5, 6, 7, 8, 9], // MLB regular season
  },
  {
    id: 'qc-yankees-game-night',
    name: 'Yankees Game at Yankee Stadium',
    kind: 'event',
    priceTier: 2,
    startTime: '19:05',
    endTime: '22:05',
    lat: 40.8296,
    lng: -73.9262,
    address: '1 E 161st St, Bronx, NY 10451',
    bookingUrl: 'https://www.mlb.com/yankees',
    description: 'Ballgame: a Bronx night game under the lights in the cathedral of baseball.',
    tags: ['outdoors'],
    months: [4, 5, 6, 7, 8, 9], // MLB regular season
  },
];
