// OutNYC curated catalog: Chelsea, Midtown & Uptown Manhattan (generated)
import type { Candidate } from '../types';

/** Restaurants + bars (kind: 'restaurant' | 'bar'). */
export const UPTOWN_PLACES: Candidate[] = [
  // ---------- Chelsea ----------
  {
    id: 'up-cookshop',
    name: 'Cookshop',
    kind: 'restaurant',
    neighborhood: 'Chelsea',
    priceTier: 3,
    durationMin: 90,
    lat: 40.746,
    lng: -74.006,
    address: '156 Tenth Ave, New York, NY 10011',
    bookingUrl: 'https://www.cookshopny.com',
    description: 'Market-driven American: sunny Tenth Ave corner where gallery-goers linger over brunch.',
    tags: ['food', 'brunch'],
    cuisine: 'American',
  },
  {
    id: 'up-empire-diner',
    name: 'Empire Diner',
    kind: 'restaurant',
    neighborhood: 'Chelsea',
    priceTier: 2,
    durationMin: 60,
    lat: 40.7473,
    lng: -74.0048,
    address: '210 Tenth Ave, New York, NY 10011',
    description: 'Classic diner: gleaming 1946 Fodero dining car serving polished comfort food.',
    tags: ['food', 'brunch'],
    cuisine: 'American',
  },
  {
    id: 'up-buddakan',
    name: 'Buddakan',
    kind: 'restaurant',
    neighborhood: 'Chelsea',
    priceTier: 4,
    durationMin: 105,
    lat: 40.7423,
    lng: -74.0049,
    address: '75 Ninth Ave, New York, NY 10011',
    bookingUrl: 'https://www.buddakannyc.com',
    description: 'Modern Chinese: cavernous gold-lit banquet hall of Sex and the City fame.',
    tags: ['food', 'late-night'],
    cuisine: 'Chinese',
  },
  {
    id: 'up-old-homestead',
    name: 'Old Homestead Steakhouse',
    kind: 'restaurant',
    neighborhood: 'Chelsea',
    priceTier: 4,
    durationMin: 105,
    lat: 40.7413,
    lng: -74.0045,
    address: '56 Ninth Ave, New York, NY 10011',
    bookingUrl: 'https://www.theoldhomesteadsteakhouse.com',
    description: 'Steakhouse: beef palace under the neon cow sign since 1868.',
    tags: ['food'],
    cuisine: 'Steakhouse',
  },
  {
    id: 'up-momoya-chelsea',
    name: 'Momoya Chelsea',
    kind: 'restaurant',
    neighborhood: 'Chelsea',
    priceTier: 3,
    durationMin: 90,
    lat: 40.7429,
    lng: -73.9957,
    address: '185 Seventh Ave, New York, NY 10011',
    bookingUrl: 'https://www.momoyanyc.com',
    description: 'Sushi restaurant: serene room turning out precise nigiri and inventive maki.',
    tags: ['food'],
    cuisine: 'Sushi',
  },
  {
    id: 'up-tia-pol',
    name: 'Tía Pol',
    kind: 'restaurant',
    neighborhood: 'Chelsea',
    priceTier: 3,
    durationMin: 90,
    lat: 40.7469,
    lng: -74.0052,
    address: '205 Tenth Ave, New York, NY 10011',
    bookingUrl: 'https://www.tiapol.com',
    description: 'Spanish tapas bar: narrow, boisterous room pouring txakoli alongside pintxos.',
    tags: ['food', 'bar'],
    cuisine: 'Mediterranean',
  },
  {
    id: 'up-sullivan-street-bakery',
    name: 'Sullivan Street Bakery',
    kind: 'restaurant',
    neighborhood: 'Chelsea',
    priceTier: 1,
    durationMin: 30,
    lat: 40.7472,
    lng: -74.0009,
    address: '236 Ninth Ave, New York, NY 10001',
    bookingUrl: 'https://www.sullivanstreetbakery.com',
    description: 'Bakery: Jim Lahey\'s crackling Roman pizza bianca and famed no-knead loaves.',
    tags: ['food', 'coffee'],
    cuisine: 'Bakery',
  },
  {
    id: 'up-joe-coffee-chelsea',
    name: 'Joe Coffee Company (Chelsea)',
    kind: 'restaurant',
    neighborhood: 'Chelsea',
    priceTier: 1,
    durationMin: 30,
    lat: 40.7458,
    lng: -74.0009,
    address: '405 W 23rd St, New York, NY 10011',
    bookingUrl: 'https://joecoffeecompany.com',
    description: 'Coffee shop: dependable NYC roaster steps from the gallery blocks.',
    tags: ['food', 'coffee'],
    cuisine: 'Coffee',
  },
  {
    id: 'up-peter-mcmanus',
    name: 'Peter McManus Café',
    kind: 'bar',
    neighborhood: 'Chelsea',
    priceTier: 1,
    durationMin: 90,
    lat: 40.7416,
    lng: -73.9964,
    address: '152 Seventh Ave, New York, NY 10011',
    description: 'Irish tavern: family-run since 1936, cheap pints in original wood booths.',
    tags: ['bar', 'late-night'],
  },
  {
    id: 'up-barracuda',
    name: 'Barracuda Lounge',
    kind: 'bar',
    neighborhood: 'Chelsea',
    priceTier: 2,
    durationMin: 90,
    lat: 40.744,
    lng: -73.9985,
    address: '275 W 22nd St, New York, NY 10011',
    description: 'Gay bar: long-running Chelsea staple with nightly drag shows in the back lounge.',
    tags: ['bar', 'late-night'],
  },
  {
    id: 'up-eagle-nyc',
    name: 'The Eagle NYC',
    kind: 'bar',
    neighborhood: 'Chelsea',
    priceTier: 2,
    durationMin: 120,
    lat: 40.7521,
    lng: -74.0031,
    address: '554 W 28th St, New York, NY 10001',
    description: 'Leather bar: two floors plus a roof deck; Sunday beer blasts are a rite of passage.',
    tags: ['bar', 'late-night', 'rooftop'],
  },
  {
    id: 'up-frying-pan',
    name: 'The Frying Pan',
    kind: 'bar',
    neighborhood: 'Chelsea',
    priceTier: 2,
    durationMin: 120,
    lat: 40.7513,
    lng: -74.0086,
    address: 'Pier 66, W 26th St & Hudson River Park, New York, NY 10011',
    description: 'Boat bar: sunset drinks on a rescued lightship moored at Pier 66 (seasonal).',
    tags: ['bar', 'outdoors'],
    months: [4, 5, 6, 7, 8, 9, 10],
  },

  // ---------- Midtown ----------
  {
    id: 'up-cho-dang-gol',
    name: 'Cho Dang Gol',
    kind: 'restaurant',
    neighborhood: 'Midtown',
    priceTier: 2,
    durationMin: 75,
    lat: 40.75,
    lng: -73.986,
    address: '55 W 35th St, New York, NY 10001',
    description: 'Korean restaurant: house-made tofu and bubbling jjigae on a quiet K-town block.',
    tags: ['food'],
    cuisine: 'Korean',
  },
  {
    id: 'up-bcd-tofu-house',
    name: 'BCD Tofu House',
    kind: 'restaurant',
    neighborhood: 'Midtown',
    priceTier: 2,
    durationMin: 75,
    lat: 40.7473,
    lng: -73.9868,
    address: '5 W 32nd St, New York, NY 10001',
    bookingUrl: 'https://www.bcdtofuhouse.com',
    description: 'Korean restaurant: soondubu specialists ladling molten tofu stews past midnight.',
    tags: ['food', 'late-night'],
    cuisine: 'Korean',
  },
  {
    id: 'up-jongro-bbq',
    name: 'Jongro BBQ',
    kind: 'restaurant',
    neighborhood: 'Midtown',
    priceTier: 3,
    durationMin: 105,
    lat: 40.7474,
    lng: -73.9872,
    address: '22 W 32nd St, 2nd Fl, New York, NY 10001',
    description: 'Korean BBQ: raucous second-floor Seoul-style grill hall with aged pork belly.',
    tags: ['food', 'late-night'],
    cuisine: 'Korean',
  },
  {
    id: 'up-keens',
    name: 'Keens Steakhouse',
    kind: 'restaurant',
    neighborhood: 'Midtown',
    priceTier: 4,
    durationMin: 120,
    lat: 40.7509,
    lng: -73.9866,
    address: '72 W 36th St, New York, NY 10018',
    bookingUrl: 'https://www.keens.com',
    description: 'Steakhouse: legendary mutton chops under 90,000 antique clay pipes since 1885.',
    tags: ['food'],
    cuisine: 'Steakhouse',
  },
  {
    id: 'up-le-bernardin',
    name: 'Le Bernardin',
    kind: 'restaurant',
    neighborhood: 'Midtown',
    priceTier: 4,
    durationMin: 150,
    lat: 40.7615,
    lng: -73.9819,
    address: '155 W 51st St, New York, NY 10019',
    bookingUrl: 'https://www.le-bernardin.com',
    description: 'Seafood temple: Eric Ripert\'s four-star shrine to impeccably precise fish.',
    tags: ['food'],
    cuisine: 'Seafood',
  },
  {
    id: 'up-grand-central-oyster-bar',
    name: 'Grand Central Oyster Bar',
    kind: 'restaurant',
    neighborhood: 'Midtown',
    priceTier: 3,
    durationMin: 90,
    lat: 40.7527,
    lng: -73.9772,
    address: '89 E 42nd St, New York, NY 10017',
    bookingUrl: 'https://www.oysterbarny.com',
    description: 'Seafood hall: century-old vaulted Guastavino-tile cellar inside Grand Central.',
    tags: ['food'],
    cuisine: 'Seafood',
  },
  {
    id: 'up-burger-joint',
    name: 'Burger Joint',
    kind: 'restaurant',
    neighborhood: 'Midtown',
    priceTier: 2,
    durationMin: 45,
    lat: 40.7643,
    lng: -73.9788,
    address: '119 W 56th St, New York, NY 10019',
    bookingUrl: 'https://www.burgerjointny.com',
    description: 'Burger counter: no-frills patties hidden behind a hotel lobby curtain.',
    tags: ['food'],
    cuisine: 'American',
  },
  {
    id: 'up-los-tacos-times-square',
    name: 'Los Tacos No. 1 (Times Square)',
    kind: 'restaurant',
    neighborhood: 'Midtown',
    priceTier: 1,
    durationMin: 30,
    lat: 40.7576,
    lng: -73.9884,
    address: '229 W 43rd St, New York, NY 10036',
    bookingUrl: 'https://www.lostacos1.com',
    description: 'Taqueria: standing-room adobada tacos that ruin all other tacos.',
    tags: ['food'],
    cuisine: 'Mexican',
  },
  {
    id: 'up-sushi-yasuda',
    name: 'Sushi Yasuda',
    kind: 'restaurant',
    neighborhood: 'Midtown',
    priceTier: 4,
    durationMin: 105,
    lat: 40.7511,
    lng: -73.9717,
    address: '204 E 43rd St, New York, NY 10017',
    bookingUrl: 'https://www.sushiyasuda.com',
    description: 'Sushi bar: hushed blond-wood temple of strictly traditional Edomae nigiri.',
    tags: ['food'],
    cuisine: 'Sushi',
  },
  {
    id: 'up-totto-ramen',
    name: 'Totto Ramen',
    kind: 'restaurant',
    neighborhood: 'Midtown',
    priceTier: 2,
    durationMin: 45,
    lat: 40.7637,
    lng: -73.9877,
    address: '366 W 52nd St, New York, NY 10019',
    bookingUrl: 'https://tottoramen.com',
    description: 'Ramen shop: blowtorched char siu atop rich chicken paitan broth.',
    tags: ['food', 'late-night'],
    cuisine: 'Japanese',
  },
  {
    id: 'up-ess-a-bagel',
    name: 'Ess-a-Bagel',
    kind: 'restaurant',
    neighborhood: 'Midtown',
    priceTier: 1,
    durationMin: 30,
    lat: 40.7563,
    lng: -73.9692,
    address: '831 Third Ave, New York, NY 10022',
    bookingUrl: 'https://www.ess-a-bagel.com',
    description: 'Bagel shop: glossy oversized hand-rolled bagels worth the weekend line.',
    tags: ['food', 'brunch'],
    cuisine: 'Bakery',
  },
  {
    id: 'up-2nd-ave-deli',
    name: '2nd Ave Deli',
    kind: 'restaurant',
    neighborhood: 'Midtown',
    priceTier: 3,
    durationMin: 75,
    lat: 40.7446,
    lng: -73.9789,
    address: '162 E 33rd St, New York, NY 10016',
    bookingUrl: 'https://www.2ndavedeli.com',
    description: 'Kosher deli: pastrami, matzo ball soup and free health salad, attitude included.',
    tags: ['food'],
    cuisine: 'Deli',
  },
  {
    id: 'up-sarges-deli',
    name: 'Sarge\'s Delicatessen & Diner',
    kind: 'restaurant',
    neighborhood: 'Midtown',
    priceTier: 2,
    durationMin: 75,
    lat: 40.7476,
    lng: -73.9757,
    address: '548 Third Ave, New York, NY 10016',
    bookingUrl: 'https://sargesdeli.com',
    description: 'Jewish deli: 24/7 pastrami institution feeding Murray Hill since 1964.',
    tags: ['food', 'late-night'],
    cuisine: 'Deli',
  },
  {
    id: 'up-pj-clarkes',
    name: 'P.J. Clarke\'s',
    kind: 'restaurant',
    neighborhood: 'Midtown',
    priceTier: 3,
    durationMin: 90,
    lat: 40.7586,
    lng: -73.9675,
    address: '915 Third Ave, New York, NY 10022',
    bookingUrl: 'https://pjclarkes.com',
    description: 'Saloon: 1884 tavern with checked tablecloths and storied bacon cheeseburgers.',
    tags: ['food', 'bar', 'late-night'],
    cuisine: 'American',
  },
  {
    id: 'up-urban-hawker',
    name: 'Urban Hawker',
    kind: 'restaurant',
    neighborhood: 'Midtown',
    priceTier: 2,
    durationMin: 60,
    lat: 40.7605,
    lng: -73.9821,
    address: '135 W 50th St, New York, NY 10020',
    bookingUrl: 'https://urbanhawker.com',
    description: 'Food hall: Singaporean hawker stalls, chicken rice to laksa, under one roof.',
    tags: ['food'],
    cuisine: 'Food hall',
  },
  {
    id: 'up-230-fifth',
    name: '230 Fifth Rooftop Bar',
    kind: 'bar',
    neighborhood: 'Midtown',
    priceTier: 3,
    durationMin: 120,
    lat: 40.7443,
    lng: -73.9879,
    address: '230 Fifth Ave, New York, NY 10001',
    bookingUrl: 'https://www.230-fifth.com',
    description: 'Rooftop bar: sprawling garden terrace with a dead-on Empire State Building view.',
    tags: ['bar', 'rooftop', 'late-night'],
  },
  {
    id: 'up-the-skylark',
    name: 'The Skylark',
    kind: 'bar',
    neighborhood: 'Midtown',
    priceTier: 3,
    durationMin: 90,
    lat: 40.7541,
    lng: -73.9891,
    address: '200 W 39th St, 30th Fl, New York, NY 10018',
    bookingUrl: 'https://theskylarknyc.com',
    description: 'Rooftop bar: 30th-floor cocktails overlooking Times Square and the Hudson.',
    tags: ['bar', 'rooftop'],
  },
  {
    id: 'up-the-campbell',
    name: 'The Campbell',
    kind: 'bar',
    neighborhood: 'Midtown',
    priceTier: 3,
    durationMin: 90,
    lat: 40.7526,
    lng: -73.9779,
    address: '15 Vanderbilt Ave, New York, NY 10017',
    description: 'Cocktail bar: restored 1920s tycoon\'s office hidden inside Grand Central.',
    tags: ['bar'],
  },
  {
    id: 'up-jimmys-corner',
    name: 'Jimmy\'s Corner',
    kind: 'bar',
    neighborhood: 'Midtown',
    priceTier: 1,
    durationMin: 75,
    lat: 40.7568,
    lng: -73.9843,
    address: '140 W 44th St, New York, NY 10036',
    description: 'Dive bar: boxing memorabilia and cheap drinks a jab away from Times Square.',
    tags: ['bar', 'late-night'],
  },
  {
    id: 'up-culture-espresso',
    name: 'Culture Espresso',
    kind: 'restaurant',
    neighborhood: 'Midtown',
    priceTier: 1,
    durationMin: 30,
    lat: 40.7519,
    lng: -73.984,
    address: '72 W 38th St, New York, NY 10018',
    bookingUrl: 'https://www.cultureespresso.com',
    description: 'Coffee shop: serious espresso and cult chocolate chip cookies near Bryant Park.',
    tags: ['food', 'coffee'],
    cuisine: 'Coffee',
  },
  {
    id: 'up-blue-bottle-rock-center',
    name: 'Blue Bottle Coffee (Rockefeller Center)',
    kind: 'restaurant',
    neighborhood: 'Midtown',
    priceTier: 2,
    durationMin: 30,
    lat: 40.7587,
    lng: -73.9787,
    address: '1 Rockefeller Plaza, New York, NY 10020',
    bookingUrl: 'https://bluebottlecoffee.com',
    description: 'Coffee shop: meticulous pour-overs beneath Rockefeller Center\'s deco towers.',
    tags: ['food', 'coffee'],
    cuisine: 'Coffee',
  },

  // ---------- Upper East Side ----------
  {
    id: 'up-cafe-sabarsky',
    name: 'Café Sabarsky',
    kind: 'restaurant',
    neighborhood: 'Upper East Side',
    priceTier: 3,
    durationMin: 75,
    lat: 40.7813,
    lng: -73.9603,
    address: '1048 Fifth Ave, New York, NY 10028',
    bookingUrl: 'https://www.neuegalerie.org',
    description: 'Viennese café: kaffeehaus with Sacher torte inside the Neue Galerie.',
    tags: ['food', 'coffee', 'brunch'],
    cuisine: 'Bakery',
  },
  {
    id: 'up-jg-melon',
    name: 'J.G. Melon',
    kind: 'restaurant',
    neighborhood: 'Upper East Side',
    priceTier: 2,
    durationMin: 60,
    lat: 40.7737,
    lng: -73.9585,
    address: '1291 Third Ave, New York, NY 10021',
    description: 'Pub burger institution: cash-only patties and cottage fries since 1972.',
    tags: ['food', 'bar', 'late-night'],
    cuisine: 'American',
  },
  {
    id: 'up-daniel',
    name: 'Daniel',
    kind: 'restaurant',
    neighborhood: 'Upper East Side',
    priceTier: 4,
    durationMin: 150,
    lat: 40.7668,
    lng: -73.9679,
    address: '60 E 65th St, New York, NY 10065',
    bookingUrl: 'https://www.danielnyc.com',
    description: 'French flagship: Daniel Boulud\'s soaring neo-classical dining room.',
    tags: ['food'],
    cuisine: 'French',
  },
  {
    id: 'up-hh-bagels-ues',
    name: 'H&H Bagels (Upper East Side)',
    kind: 'restaurant',
    neighborhood: 'Upper East Side',
    priceTier: 1,
    durationMin: 30,
    lat: 40.7743,
    lng: -73.9528,
    address: '1551 Second Ave, New York, NY 10028',
    description: 'Bagel shop: the storied name still rolling hot, plump classics daily.',
    tags: ['food', 'brunch'],
    cuisine: 'Bakery',
  },
  {
    id: 'up-lexington-candy-shop',
    name: 'Lexington Candy Shop',
    kind: 'restaurant',
    neighborhood: 'Upper East Side',
    priceTier: 2,
    durationMin: 60,
    lat: 40.7772,
    lng: -73.9563,
    address: '1226 Lexington Ave, New York, NY 10028',
    description: 'Luncheonette: 1925 soda fountain still making egg creams the original way.',
    tags: ['food', 'brunch'],
    cuisine: 'American',
  },
  {
    id: 'up-serendipity-3',
    name: 'Serendipity 3',
    kind: 'restaurant',
    neighborhood: 'Upper East Side',
    priceTier: 3,
    durationMin: 75,
    lat: 40.7618,
    lng: -73.965,
    address: '225 E 60th St, New York, NY 10022',
    bookingUrl: 'https://serendipity3.com',
    description: 'Dessert parlor: home of the frozen hot chocolate and Tiffany-lamp whimsy.',
    tags: ['food'],
    cuisine: 'American',
  },
  {
    id: 'up-uva',
    name: 'Uva',
    kind: 'restaurant',
    neighborhood: 'Upper East Side',
    priceTier: 3,
    durationMin: 90,
    lat: 40.7714,
    lng: -73.9542,
    address: '1486 Second Ave, New York, NY 10075',
    bookingUrl: 'https://www.uvanyc.com',
    description: 'Italian wine bar: candlelit rustic rooms and a vine-covered back garden.',
    tags: ['food', 'bar', 'late-night'],
    cuisine: 'Italian',
  },
  {
    id: 'up-sushi-of-gari',
    name: 'Sushi of Gari',
    kind: 'restaurant',
    neighborhood: 'Upper East Side',
    priceTier: 4,
    durationMin: 105,
    lat: 40.7721,
    lng: -73.9522,
    address: '402 E 78th St, New York, NY 10075',
    bookingUrl: 'https://sushiofgari.com',
    description: 'Sushi bar: Gari\'s famously creative topped-nigiri omakase.',
    tags: ['food'],
    cuisine: 'Sushi',
  },
  {
    id: 'up-the-penrose',
    name: 'The Penrose',
    kind: 'bar',
    neighborhood: 'Upper East Side',
    priceTier: 2,
    durationMin: 90,
    lat: 40.7757,
    lng: -73.9518,
    address: '1590 Second Ave, New York, NY 10028',
    description: 'Gastropub: exposed-brick craft-beer hangout that packs in weekend brunch.',
    tags: ['bar', 'brunch', 'late-night'],
  },
  {
    id: 'up-bemelmans-bar',
    name: 'Bemelmans Bar',
    kind: 'bar',
    neighborhood: 'Upper East Side',
    priceTier: 4,
    durationMin: 90,
    lat: 40.7745,
    lng: -73.9632,
    address: '35 E 76th St, New York, NY 10021',
    description: 'Hotel bar: Madeline murals and nightly piano at the Carlyle.',
    tags: ['bar', 'live music'],
  },
  {
    id: 'up-ralphs-coffee',
    name: 'Ralph\'s Coffee',
    kind: 'restaurant',
    neighborhood: 'Upper East Side',
    priceTier: 2,
    durationMin: 30,
    lat: 40.7729,
    lng: -73.9663,
    address: '888 Madison Ave, New York, NY 10021',
    description: 'Coffee shop: espresso with green-and-gold polish at Ralph Lauren\'s flagship.',
    tags: ['food', 'coffee'],
    cuisine: 'Coffee',
  },

  // ---------- Upper West Side ----------
  {
    id: 'up-zabars-cafe',
    name: 'Zabar\'s Café',
    kind: 'restaurant',
    neighborhood: 'Upper West Side',
    priceTier: 2,
    durationMin: 45,
    lat: 40.7841,
    lng: -73.9809,
    address: '2245 Broadway, New York, NY 10024',
    bookingUrl: 'https://www.zabars.com',
    description: 'Deli counter: smoked-fish mecca since 1934; lox and coffee at the café.',
    tags: ['food', 'coffee', 'brunch'],
    cuisine: 'Deli',
  },
  {
    id: 'up-levain-bakery',
    name: 'Levain Bakery',
    kind: 'restaurant',
    neighborhood: 'Upper West Side',
    priceTier: 1,
    durationMin: 30,
    lat: 40.7791,
    lng: -73.98,
    address: '167 W 74th St, New York, NY 10023',
    bookingUrl: 'https://levainbakery.com',
    description: 'Bakery: the six-ounce gooey chocolate-chip walnut cookie that launched pilgrimages.',
    tags: ['food'],
    cuisine: 'Bakery',
  },
  {
    id: 'up-barney-greengrass',
    name: 'Barney Greengrass',
    kind: 'restaurant',
    neighborhood: 'Upper West Side',
    priceTier: 3,
    durationMin: 75,
    lat: 40.7876,
    lng: -73.9754,
    address: '541 Amsterdam Ave, New York, NY 10024',
    bookingUrl: 'https://barneygreengrass.com',
    description: 'Appetizing deli: the Sturgeon King, sable and eggs largely unchanged since 1908.',
    tags: ['food', 'brunch'],
    cuisine: 'Deli',
  },
  {
    id: 'up-jacobs-pickles',
    name: 'Jacob\'s Pickles',
    kind: 'restaurant',
    neighborhood: 'Upper West Side',
    priceTier: 2,
    durationMin: 90,
    lat: 40.7864,
    lng: -73.9763,
    address: '509 Amsterdam Ave, New York, NY 10024',
    bookingUrl: 'https://www.jacobspickles.com',
    description: 'Southern kitchen: biscuits, pickle flights and fried chicken until late.',
    tags: ['food', 'brunch', 'late-night'],
    cuisine: 'Southern',
  },
  {
    id: 'up-grays-papaya',
    name: 'Gray\'s Papaya',
    kind: 'restaurant',
    neighborhood: 'Upper West Side',
    priceTier: 1,
    durationMin: 20,
    lat: 40.7783,
    lng: -73.9818,
    address: '2090 Broadway, New York, NY 10023',
    description: 'Hot dog stand: snappy franks and papaya drink, an around-the-clock NYC ritual.',
    tags: ['food', 'late-night'],
    cuisine: 'American',
  },
  {
    id: 'up-celeste',
    name: 'Celeste',
    kind: 'restaurant',
    neighborhood: 'Upper West Side',
    priceTier: 2,
    durationMin: 90,
    lat: 40.786,
    lng: -73.9769,
    address: '502 Amsterdam Ave, New York, NY 10024',
    description: 'Neapolitan trattoria: wood-fired pies and cloudlike fresh ricotta, cash only.',
    tags: ['food'],
    cuisine: 'Italian',
  },
  {
    id: 'up-sushi-yasaka',
    name: 'Sushi Yasaka',
    kind: 'restaurant',
    neighborhood: 'Upper West Side',
    priceTier: 3,
    durationMin: 90,
    lat: 40.7787,
    lng: -73.9836,
    address: '251 W 72nd St, New York, NY 10023',
    bookingUrl: 'https://www.sushiyasaka.com',
    description: 'Sushi bar: remarkable-value omakase a short walk from Lincoln Center.',
    tags: ['food'],
    cuisine: 'Sushi',
  },
  {
    id: 'up-bar-boulud',
    name: 'Bar Boulud',
    kind: 'restaurant',
    neighborhood: 'Upper West Side',
    priceTier: 3,
    durationMin: 105,
    lat: 40.7717,
    lng: -73.9822,
    address: '1900 Broadway, New York, NY 10023',
    bookingUrl: 'https://www.barboulud.com',
    description: 'French bistro: charcuterie and burgundy directly across from Lincoln Center.',
    tags: ['food', 'bar'],
    cuisine: 'French',
  },
  {
    id: 'up-flor-de-mayo',
    name: 'Flor de Mayo',
    kind: 'restaurant',
    neighborhood: 'Upper West Side',
    priceTier: 2,
    durationMin: 60,
    lat: 40.7993,
    lng: -73.9687,
    address: '2651 Broadway, New York, NY 10025',
    description: 'Chino-Latino: Peruvian rotisserie chicken with fried rice, an Uptown hybrid classic.',
    tags: ['food'],
    cuisine: 'Peruvian',
  },
  {
    id: 'up-cafe-luxembourg',
    name: 'Café Luxembourg',
    kind: 'restaurant',
    neighborhood: 'Upper West Side',
    priceTier: 3,
    durationMin: 105,
    lat: 40.7778,
    lng: -73.9827,
    address: '200 W 70th St, New York, NY 10023',
    bookingUrl: 'https://cafeluxembourg.com',
    description: 'French brasserie: zinc-and-mirror charmer drawing pre-show and late crowds.',
    tags: ['food', 'brunch', 'late-night'],
    cuisine: 'French',
  },
  {
    id: 'up-dead-poet',
    name: 'The Dead Poet',
    kind: 'bar',
    neighborhood: 'Upper West Side',
    priceTier: 1,
    durationMin: 90,
    lat: 40.7852,
    lng: -73.9772,
    address: '450 Amsterdam Ave, New York, NY 10024',
    description: 'Literary dive: Guinness and bourbon under portraits of hard-drinking writers.',
    tags: ['bar', 'late-night'],
  },
  {
    id: 'up-joe-coffee-uws',
    name: 'Joe Coffee Company (Columbus Ave)',
    kind: 'restaurant',
    neighborhood: 'Upper West Side',
    priceTier: 1,
    durationMin: 30,
    lat: 40.7862,
    lng: -73.9723,
    address: '514 Columbus Ave, New York, NY 10024',
    bookingUrl: 'https://joecoffeecompany.com',
    description: 'Coffee shop: friendly Columbus Ave outpost perfect before a museum morning.',
    tags: ['food', 'coffee'],
    cuisine: 'Coffee',
  },

  // ---------- Harlem ----------
  {
    id: 'up-amy-ruths',
    name: 'Amy Ruth\'s',
    kind: 'restaurant',
    neighborhood: 'Harlem',
    priceTier: 2,
    durationMin: 75,
    lat: 40.802,
    lng: -73.9497,
    address: '113 W 116th St, New York, NY 10026',
    bookingUrl: 'https://amyruths.com',
    description: 'Soul food: chicken-and-waffle plates named for gospel greats and Harlem heroes.',
    tags: ['food', 'brunch'],
    cuisine: 'Southern',
  },
  {
    id: 'up-melbas',
    name: 'Melba\'s',
    kind: 'restaurant',
    neighborhood: 'Harlem',
    priceTier: 2,
    durationMin: 90,
    lat: 40.8024,
    lng: -73.9563,
    address: '300 W 114th St, New York, NY 10026',
    bookingUrl: 'https://melbasrestaurant.com',
    description: 'Soul food: Melba Wilson\'s wine-braised short ribs and eggnog waffles.',
    tags: ['food', 'brunch'],
    cuisine: 'Southern',
  },
  {
    id: 'up-charles-pan-fried-chicken',
    name: 'Charles\' Pan-Fried Chicken',
    kind: 'restaurant',
    neighborhood: 'Harlem',
    priceTier: 2,
    durationMin: 45,
    lat: 40.8283,
    lng: -73.941,
    address: '2839 Frederick Douglass Blvd, New York, NY 10039',
    description: 'Southern counter: legendary cast-iron pan-fried chicken worth the trek uptown.',
    tags: ['food'],
    cuisine: 'Southern',
  },
  {
    id: 'up-dinosaur-bbq',
    name: 'Dinosaur Bar-B-Que',
    kind: 'restaurant',
    neighborhood: 'Harlem',
    priceTier: 2,
    durationMin: 90,
    lat: 40.8172,
    lng: -73.9603,
    address: '700 W 125th St, New York, NY 10027',
    bookingUrl: 'https://www.dinosaurbarbque.com',
    description: 'BBQ joint: ribs and blues in a roadhouse under the Riverside Drive viaduct.',
    tags: ['food', 'bar'],
    cuisine: 'Southern',
  },
  {
    id: 'up-harlem-shake',
    name: 'Harlem Shake',
    kind: 'restaurant',
    neighborhood: 'Harlem',
    priceTier: 1,
    durationMin: 45,
    lat: 40.8064,
    lng: -73.944,
    address: '100 W 124th St, New York, NY 10027',
    bookingUrl: 'https://harlemshakenyc.com',
    description: 'Burger joint: retro diner vibes, jerk fries and a wall of Harlem legends.',
    tags: ['food'],
    cuisine: 'American',
  },
  {
    id: 'up-patsys-pizzeria',
    name: 'Patsy\'s Pizzeria (East Harlem)',
    kind: 'restaurant',
    neighborhood: 'Harlem',
    priceTier: 2,
    durationMin: 60,
    lat: 40.7973,
    lng: -73.935,
    address: '2287 First Ave, New York, NY 10035',
    description: 'Coal-oven pizzeria: thin charred slices from the original 1933 East Harlem oven.',
    tags: ['food'],
    cuisine: 'Pizza',
  },
  {
    id: 'up-vinateria',
    name: 'Vinatería',
    kind: 'restaurant',
    neighborhood: 'Harlem',
    priceTier: 3,
    durationMin: 90,
    lat: 40.8049,
    lng: -73.9547,
    address: '2211 Frederick Douglass Blvd, New York, NY 10026',
    bookingUrl: 'https://www.vinaterianyc.com',
    description: 'Italian-Spanish kitchen: moody candlelit pastas on Frederick Douglass Blvd.',
    tags: ['food', 'bar'],
    cuisine: 'Italian',
  },
  {
    id: 'up-corner-social',
    name: 'Corner Social',
    kind: 'restaurant',
    neighborhood: 'Harlem',
    priceTier: 2,
    durationMin: 90,
    lat: 40.8078,
    lng: -73.9433,
    address: '321 Lenox Ave, New York, NY 10027',
    bookingUrl: 'https://cornersocialnyc.com',
    description: 'Neighborhood bistro: lively Lenox Ave corner for brunch and people-watching.',
    tags: ['food', 'bar', 'brunch', 'late-night'],
    cuisine: 'American',
  },
  {
    id: 'up-harlem-hops',
    name: 'Harlem Hops',
    kind: 'bar',
    neighborhood: 'Harlem',
    priceTier: 2,
    durationMin: 90,
    lat: 40.814,
    lng: -73.9437,
    address: '2268 Adam Clayton Powell Jr Blvd, New York, NY 10030',
    bookingUrl: 'https://harlemhops.com',
    description: 'Beer bar: Black-owned craft taproom pouring African-diaspora brews.',
    tags: ['bar'],
  },
  {
    id: 'up-shrine',
    name: 'Shrine World Music Venue',
    kind: 'bar',
    neighborhood: 'Harlem',
    priceTier: 1,
    durationMin: 120,
    lat: 40.8142,
    lng: -73.9436,
    address: '2271 Adam Clayton Powell Jr Blvd, New York, NY 10030',
    description: 'Music bar: Afrobeat, jazz and funk on a tiny stage nearly every night, no cover.',
    tags: ['bar', 'live music', 'late-night'],
  },
  {
    id: 'up-double-dutch-espresso',
    name: 'Double Dutch Espresso',
    kind: 'restaurant',
    neighborhood: 'Harlem',
    priceTier: 1,
    durationMin: 30,
    lat: 40.8038,
    lng: -73.9554,
    address: '2194 Frederick Douglass Blvd, New York, NY 10026',
    description: 'Coffee shop: snug espresso nook fueling Frederick Douglass Blvd mornings.',
    tags: ['food', 'coffee'],
    cuisine: 'Coffee',
  },
];

/** Activities + fixed-time events (kind: 'activity' | 'event'). */
export const UPTOWN_EVENTS: Candidate[] = [
  // ---------- Activities ----------
  {
    id: 'up-bethesda-terrace-loop',
    name: 'Central Park: Bethesda Terrace & the Mall',
    kind: 'activity',
    neighborhood: 'Upper West Side',
    priceTier: 1,
    durationMin: 90,
    lat: 40.7736,
    lng: -73.9708,
    address: 'Mid-Park at 72nd St, Central Park, New York, NY',
    bookingUrl: 'https://www.centralparknyc.org',
    description: 'Park walk: the Mall\'s elm cathedral down to Bethesda Fountain and the lake.',
    tags: ['outdoors', 'walk'],
  },
  {
    id: 'up-conservatory-garden',
    name: 'Central Park: Conservatory Garden',
    kind: 'activity',
    neighborhood: 'Upper East Side',
    priceTier: 1,
    durationMin: 60,
    lat: 40.7942,
    lng: -73.9522,
    address: 'Fifth Ave at 105th St, Central Park, New York, NY',
    bookingUrl: 'https://www.centralparknyc.org',
    description: 'Formal garden: Central Park\'s quiet six acres of fountains and crabapple allées.',
    tags: ['outdoors', 'walk'],
  },
  {
    id: 'up-loeb-boathouse-rowboats',
    name: 'Central Park: Loeb Boathouse Rowboats',
    kind: 'activity',
    neighborhood: 'Upper East Side',
    priceTier: 2,
    durationMin: 90,
    lat: 40.7752,
    lng: -73.9686,
    address: 'E 72nd St & Park Drive North, Central Park, New York, NY',
    description: 'Rowboat outing: rent a boat and drift the lake past Bow Bridge.',
    tags: ['outdoors'],
  },
  {
    id: 'up-belvedere-castle-ramble',
    name: 'Central Park: Belvedere Castle & the Ramble',
    kind: 'activity',
    neighborhood: 'Upper West Side',
    priceTier: 1,
    durationMin: 75,
    lat: 40.7794,
    lng: -73.9692,
    address: 'Mid-Park at 79th St, Central Park, New York, NY',
    bookingUrl: 'https://www.centralparknyc.org',
    description: 'Park walk: winding Ramble trails up to the castle\'s Turtle Pond lookout.',
    tags: ['outdoors', 'walk'],
  },
  {
    id: 'up-the-met',
    name: 'The Metropolitan Museum of Art',
    kind: 'activity',
    neighborhood: 'Upper East Side',
    priceTier: 2,
    durationMin: 150,
    lat: 40.7794,
    lng: -73.9632,
    address: '1000 Fifth Ave, New York, NY 10028',
    bookingUrl: 'https://www.metmuseum.org',
    description: 'Art museum: two million works; do one wing well, plus the roof in season.',
    tags: ['art'],
  },
  {
    id: 'up-moma',
    name: 'Museum of Modern Art (MoMA)',
    kind: 'activity',
    neighborhood: 'Midtown',
    priceTier: 3,
    durationMin: 120,
    lat: 40.7614,
    lng: -73.9776,
    address: '11 W 53rd St, New York, NY 10019',
    bookingUrl: 'https://www.moma.org',
    description: 'Art museum: Starry Night, Les Demoiselles and the modern canon on 53rd St.',
    tags: ['art'],
  },
  {
    id: 'up-natural-history-museum',
    name: 'American Museum of Natural History',
    kind: 'activity',
    neighborhood: 'Upper West Side',
    priceTier: 2,
    durationMin: 150,
    lat: 40.7813,
    lng: -73.974,
    address: '200 Central Park West, New York, NY 10024',
    bookingUrl: 'https://www.amnh.org',
    description: 'Natural history museum: dinosaur halls, the blue whale and the Rose Center.',
    tags: ['art'],
  },
  {
    id: 'up-guggenheim',
    name: 'Solomon R. Guggenheim Museum',
    kind: 'activity',
    neighborhood: 'Upper East Side',
    priceTier: 3,
    durationMin: 90,
    lat: 40.783,
    lng: -73.959,
    address: '1071 Fifth Ave, New York, NY 10128',
    bookingUrl: 'https://www.guggenheim.org',
    description: 'Art museum: ride Frank Lloyd Wright\'s spiral rotunda top to bottom.',
    tags: ['art'],
  },
  {
    id: 'up-frick-collection',
    name: 'The Frick Collection',
    kind: 'activity',
    neighborhood: 'Upper East Side',
    priceTier: 3,
    durationMin: 90,
    lat: 40.7712,
    lng: -73.9673,
    address: '1 E 70th St, New York, NY 10021',
    bookingUrl: 'https://www.frick.org',
    description: 'Art museum: Gilded Age mansion of Vermeers, freshly reopened after renovation.',
    tags: ['art'],
  },
  {
    id: 'up-morgan-library',
    name: 'The Morgan Library & Museum',
    kind: 'activity',
    neighborhood: 'Midtown',
    priceTier: 2,
    durationMin: 90,
    lat: 40.7492,
    lng: -73.9814,
    address: '225 Madison Ave, New York, NY 10016',
    bookingUrl: 'https://www.themorgan.org',
    description: 'Library museum: Pierpont Morgan\'s jewel-box study and tiered vault of books.',
    tags: ['art'],
  },
  {
    id: 'up-edge-hudson-yards',
    name: 'Edge at Hudson Yards',
    kind: 'activity',
    neighborhood: 'Midtown',
    priceTier: 3,
    durationMin: 75,
    lat: 40.7539,
    lng: -74.0009,
    address: '30 Hudson Yards, New York, NY 10001',
    bookingUrl: 'https://www.edgenyc.com',
    description: 'Observation deck: glass-floored ledge jutting 100 stories over Hudson Yards.',
    tags: ['outdoors'],
  },
  {
    id: 'up-hudson-yards-vessel',
    name: 'Hudson Yards & the Vessel',
    kind: 'activity',
    neighborhood: 'Midtown',
    priceTier: 1,
    durationMin: 60,
    lat: 40.7538,
    lng: -74.0022,
    address: '20 Hudson Yards, New York, NY 10001',
    bookingUrl: 'https://www.hudsonyardsnewyork.com',
    description: 'Plaza stroll: circle Heatherwick\'s copper honeycomb amid the glassy new district.',
    tags: ['outdoors', 'walk'],
  },
  {
    id: 'up-top-of-the-rock',
    name: 'Top of the Rock',
    kind: 'activity',
    neighborhood: 'Midtown',
    priceTier: 3,
    durationMin: 75,
    lat: 40.7587,
    lng: -73.9787,
    address: '30 Rockefeller Plaza, New York, NY 10112',
    bookingUrl: 'https://www.rockefellercenter.com',
    description: 'Observation deck: the classic skyline shot with the Empire State in frame.',
    tags: ['outdoors'],
  },
  {
    id: 'up-bryant-park',
    name: 'Bryant Park',
    kind: 'activity',
    neighborhood: 'Midtown',
    priceTier: 1,
    durationMin: 60,
    lat: 40.7536,
    lng: -73.9832,
    address: 'Sixth Ave & W 42nd St, New York, NY 10018',
    bookingUrl: 'https://bryantpark.org',
    description: 'Park break: lawn, kiosks and reading room behind the Public Library lions.',
    tags: ['outdoors', 'walk'],
  },
  {
    id: 'up-roosevelt-island-tram',
    name: 'Tramway ride at Roosevelt Island',
    kind: 'activity',
    neighborhood: 'Upper East Side',
    priceTier: 1,
    durationMin: 60,
    lat: 40.7615,
    lng: -73.9641,
    address: 'E 59th St & Second Ave, New York, NY 10022',
    description: 'Aerial tram: ride the cable car over the East River for a transit-fare view.',
    tags: ['outdoors'],
  },
  {
    id: 'up-riverside-park-walk',
    name: 'Riverside Park Promenade',
    kind: 'activity',
    neighborhood: 'Upper West Side',
    priceTier: 1,
    durationMin: 75,
    lat: 40.7907,
    lng: -73.98,
    address: 'Riverside Dr & W 89th St, New York, NY 10024',
    description: 'Waterfront walk: Hudson promenade north from the 79th St Boat Basin.',
    tags: ['outdoors', 'walk'],
  },
  {
    id: 'up-morningside-columbia-stroll',
    name: 'Morningside Heights & Columbia Stroll',
    kind: 'activity',
    neighborhood: 'Upper West Side',
    priceTier: 1,
    durationMin: 75,
    lat: 40.8075,
    lng: -73.9626,
    address: 'Columbia University, Broadway & W 116th St, New York, NY 10027',
    description: 'Campus walk: Low Library steps, quiet quads and Morningside brownstones.',
    tags: ['outdoors', 'walk'],
  },
  {
    id: 'up-st-john-the-divine',
    name: 'Cathedral of St. John the Divine',
    kind: 'activity',
    neighborhood: 'Upper West Side',
    priceTier: 1,
    durationMin: 60,
    lat: 40.8036,
    lng: -73.9618,
    address: '1047 Amsterdam Ave, New York, NY 10025',
    bookingUrl: 'https://www.stjohndivine.org',
    description: 'Cathedral visit: vast unfinished Gothic nave with peacocks in the garden.',
    tags: ['art', 'walk'],
  },
  {
    id: 'up-chelsea-gallery-row',
    name: 'Chelsea Gallery Row',
    kind: 'activity',
    neighborhood: 'Chelsea',
    priceTier: 1,
    durationMin: 90,
    lat: 40.748,
    lng: -74.0048,
    address: 'W 20th–26th Sts between Tenth & Eleventh Aves, New York, NY',
    description: 'Gallery crawl: free contemporary art across 200-plus West Chelsea galleries.',
    tags: ['art', 'walk'],
  },
  {
    id: 'up-little-island',
    name: 'Little Island',
    kind: 'activity',
    neighborhood: 'Chelsea',
    priceTier: 1,
    durationMin: 60,
    lat: 40.742,
    lng: -74.01,
    address: 'Pier 55, Hudson River Park at W 13th St, New York, NY 10014',
    bookingUrl: 'https://littleisland.org',
    description: 'Park visit: Heatherwick\'s tulip-pier park floating over the Hudson.',
    tags: ['outdoors', 'walk'],
  },
  {
    id: 'up-strivers-row-walk',
    name: 'Strivers\' Row & Harlem Brownstone Walk',
    kind: 'activity',
    neighborhood: 'Harlem',
    priceTier: 1,
    durationMin: 75,
    lat: 40.8172,
    lng: -73.9427,
    address: 'W 138th & 139th Sts between Adam Clayton Powell Jr & Frederick Douglass Blvds, New York, NY',
    description: 'Brownstone walk: 1890s King Model Houses along Harlem\'s grandest blocks.',
    tags: ['outdoors', 'walk'],
  },
  {
    id: 'up-grand-central-visit',
    name: 'Grand Central Terminal Visit',
    kind: 'activity',
    neighborhood: 'Midtown',
    priceTier: 1,
    durationMin: 45,
    lat: 40.7527,
    lng: -73.9772,
    address: '89 E 42nd St, New York, NY 10017',
    bookingUrl: 'https://www.grandcentralterminal.com',
    description: 'Landmark visit: constellation ceiling, whispering gallery and marble ramps.',
    tags: ['walk', 'art'],
  },

  // ---------- Fixed-time events ----------
  {
    id: 'up-birdland-jazz',
    name: 'Jazz at Birdland',
    kind: 'event',
    neighborhood: 'Midtown',
    priceTier: 3,
    startTime: '19:00',
    endTime: '20:30',
    lat: 40.7593,
    lng: -73.9902,
    address: '315 W 44th St, New York, NY 10036',
    bookingUrl: 'https://www.birdlandjazz.com',
    description: 'Jazz club: the Jazz Corner of the World still swings nightly on 44th St.',
    tags: ['live music'],
  },
  {
    id: 'up-dizzys-club',
    name: 'Dizzy\'s Club at Jazz at Lincoln Center',
    kind: 'event',
    neighborhood: 'Midtown',
    priceTier: 3,
    startTime: '19:30',
    endTime: '21:00',
    lat: 40.7685,
    lng: -73.9832,
    address: '10 Columbus Circle, 5th Fl, New York, NY 10019',
    bookingUrl: 'https://www.jazz.org',
    description: 'Jazz club: sets against a glass wall of Central Park lights at Columbus Circle.',
    tags: ['live music'],
  },
  {
    id: 'up-smoke-jazz',
    name: 'Smoke Jazz & Supper Club',
    kind: 'event',
    neighborhood: 'Upper West Side',
    priceTier: 3,
    startTime: '21:00',
    endTime: '22:30',
    lat: 40.8022,
    lng: -73.9679,
    address: '2751 Broadway, New York, NY 10025',
    bookingUrl: 'https://www.smokejazz.com',
    description: 'Jazz club: intimate uptown room with serious bookings and supper-club vibes.',
    tags: ['live music', 'food'],
  },
  {
    id: 'up-ny-philharmonic',
    name: 'New York Philharmonic at David Geffen Hall',
    kind: 'event',
    neighborhood: 'Upper West Side',
    priceTier: 3,
    startTime: '19:30',
    endTime: '21:30',
    lat: 40.7727,
    lng: -73.9832,
    address: '10 Lincoln Center Plaza, New York, NY 10023',
    bookingUrl: 'https://nyphil.org',
    description: 'Orchestra concert: the Philharmonic in the warmly rebuilt David Geffen Hall.',
    tags: ['live music', 'art'],
  },
  {
    id: 'up-carnegie-hall',
    name: 'Concert at Carnegie Hall',
    kind: 'event',
    neighborhood: 'Midtown',
    priceTier: 3,
    startTime: '20:00',
    endTime: '22:00',
    lat: 40.7651,
    lng: -73.9799,
    address: '881 Seventh Ave, New York, NY 10019',
    bookingUrl: 'https://www.carnegiehall.org',
    description: 'Concert hall: world-class recitals under Gilded Age gilt since 1891.',
    tags: ['live music', 'art'],
  },
  {
    id: 'up-broadway-show',
    name: 'Broadway Show (Theater District)',
    kind: 'event',
    neighborhood: 'Midtown',
    priceTier: 4,
    startTime: '19:00',
    endTime: '21:30',
    lat: 40.759,
    lng: -73.9845,
    address: 'Theater District, Broadway & W 44th St, New York, NY 10036',
    description: 'Broadway show: grab a marquee musical; rush and lottery seats soften the price.',
    tags: ['art'],
  },
  {
    id: 'up-stand-up-ny',
    name: 'Stand Up NY Comedy Show',
    kind: 'event',
    neighborhood: 'Upper West Side',
    priceTier: 2,
    startTime: '20:00',
    endTime: '21:30',
    lat: 40.7828,
    lng: -73.9797,
    address: '236 W 78th St, New York, NY 10024',
    bookingUrl: 'https://standupny.com',
    description: 'Comedy club: tight UWS room where big names drop in unannounced.',
    tags: ['comedy'],
  },
  {
    id: 'up-gotham-comedy-club',
    name: 'Gotham Comedy Club Show',
    kind: 'event',
    neighborhood: 'Chelsea',
    priceTier: 2,
    startTime: '19:30',
    endTime: '21:00',
    lat: 40.7444,
    lng: -73.9962,
    address: '208 W 23rd St, New York, NY 10011',
    bookingUrl: 'https://gothamcomedyclub.com',
    description: 'Comedy club: polished Chelsea showcase room with rotating headliner lineups.',
    tags: ['comedy'],
  },
  {
    id: 'up-harlem-gospel-fcbc',
    name: 'Sunday Gospel at First Corinthian Baptist Church',
    kind: 'event',
    neighborhood: 'Harlem',
    priceTier: 1,
    startTime: '09:30',
    endTime: '11:00',
    lat: 40.8028,
    lng: -73.9518,
    address: '1912 Adam Clayton Powell Jr Blvd, New York, NY 10026',
    bookingUrl: 'https://www.fcbcnyc.org',
    description: 'Gospel service: soaring Sunday worship inside a former 1913 movie palace.',
    tags: ['live music'],
    daysOfWeek: [0],
  },
  {
    id: 'up-mintons-playhouse',
    name: 'Jazz at Minton\'s Playhouse',
    kind: 'event',
    neighborhood: 'Harlem',
    priceTier: 3,
    startTime: '19:00',
    endTime: '21:00',
    lat: 40.8043,
    lng: -73.9505,
    address: '206 W 118th St, New York, NY 10026',
    description: 'Jazz supper club: bebop was born here; dinner sets keep the flame lit.',
    tags: ['live music', 'food'],
  },
];
