// =============================================================================
// OutNYC — NYC seed data (lib/constants.ts)
// =============================================================================
// The curated NYC guide that powers the zero-key experience.
//   - SEED_PROFILE mirrors the profile seed in supabase/migrations/0001_init.sql
//   - BUCKET_SEED  mirrors the bucket_list seed in the same migration
//   - SEED_EVENTS / SEED_PLACES feed the heuristic planner and providers
// Timing tags the planner understands: 'coffee', 'brunch', 'late-night',
// 'rooftop'. Keep BUCKET_SEED and SEED_PROFILE in sync with the SQL seed.
// =============================================================================

import type { BucketItem, Candidate, Profile } from './types';

export const NEIGHBORHOODS: string[] = [
  'West Village',
  'East Village',
  'Lower East Side',
  'Williamsburg',
  'Chelsea',
  'SoHo',
  'Greenpoint',
  'DUMBO',
  'Financial District',
  'Harlem',
  'Astoria',
  'Bushwick',
];

export const INTEREST_TAGS: string[] = [
  'live music',
  'food',
  'art',
  'outdoors',
  'bar',
  'comedy',
  'film',
  'walk',
];

/** Single-user profile seed. Mirrors the SQL profile insert. */
export const SEED_PROFILE: Profile = {
  displayName: 'You',
  partySize: 2,
  defaultNeighborhoods: ['West Village', 'Lower East Side', 'Williamsburg'],
  priceRange: { min: 1, max: 3 },
  interests: ['live music', 'food', 'art', 'outdoors'],
  homeBase: 'West Village',
  onboarded: false,
};

/** Bucket-list seed. Mirrors BUCKET_SEED in 0001_init.sql (same order + fields). */
export const BUCKET_SEED: BucketItem[] = [
  {
    id: 'seed-bucket-0',
    title: 'Catch sunset on the High Line',
    note: 'Best near sunset; walk the whole stretch.',
    neighborhood: 'Chelsea',
    priceTier: 1,
    tags: ['outdoors', 'walk'],
    done: false,
    sortOrder: 0,
  },
  {
    id: 'seed-bucket-1',
    title: 'Jazz set at the Village Vanguard',
    note: 'Reserve ahead; iconic basement room.',
    neighborhood: 'West Village',
    priceTier: 3,
    tags: ['live music'],
    done: false,
    sortOrder: 1,
  },
  {
    id: 'seed-bucket-2',
    title: 'Slice crawl through the East Village',
    note: 'Hit three classic spots in one night.',
    neighborhood: 'East Village',
    priceTier: 1,
    tags: ['food'],
    done: false,
    sortOrder: 2,
  },
  {
    id: 'seed-bucket-3',
    title: 'Smorgasburg on a Saturday',
    note: 'Go hungry; cash and card.',
    neighborhood: 'Williamsburg',
    priceTier: 2,
    tags: ['food', 'outdoors'],
    done: false,
    sortOrder: 3,
  },
  {
    id: 'seed-bucket-4',
    title: 'Late-night ramen in the East Village',
    note: 'For after a show.',
    neighborhood: 'East Village',
    priceTier: 2,
    tags: ['food', 'late-night'],
    done: false,
    sortOrder: 4,
  },
  {
    id: 'seed-bucket-5',
    title: 'Rooftop drinks in Lower Manhattan',
    note: 'Sunset views over the harbor.',
    neighborhood: 'Financial District',
    priceTier: 3,
    tags: ['bar', 'rooftop'],
    done: false,
    sortOrder: 5,
  },
  {
    id: 'seed-bucket-6',
    title: 'Brooklyn Bridge walk at golden hour',
    note: 'Start Manhattan side, end in DUMBO.',
    neighborhood: 'DUMBO',
    priceTier: 1,
    tags: ['outdoors', 'walk'],
    done: false,
    sortOrder: 6,
  },
  {
    id: 'seed-bucket-7',
    title: 'See a show at the Comedy Cellar',
    note: 'Standby line moves fast on weeknights.',
    neighborhood: 'West Village',
    priceTier: 2,
    tags: ['comedy'],
    done: false,
    sortOrder: 7,
  },
];

/** Curated NYC seed events (have fixed start/end times). */
export const SEED_EVENTS: Candidate[] = [
  {
    id: 'evt-vanguard',
    name: 'Live Jazz at the Village Vanguard',
    kind: 'event',
    neighborhood: 'West Village',
    priceTier: 3,
    startTime: '20:00',
    endTime: '22:00',
    lat: 40.7359,
    lng: -74.0008,
    address: '178 7th Ave S, New York, NY',
    bookingUrl: 'https://villagevanguard.com/',
    description: 'The most storied basement jazz room in the city, in business since 1935.',
    tags: ['live music'],
  },
  {
    id: 'evt-comedy-cellar',
    name: 'Stand-up at the Comedy Cellar',
    kind: 'event',
    neighborhood: 'West Village',
    priceTier: 2,
    startTime: '21:00',
    endTime: '22:30',
    lat: 40.7301,
    lng: -74.0007,
    address: '117 MacDougal St, New York, NY',
    bookingUrl: 'https://www.comedycellar.com/',
    description: 'Low-ceilinged MacDougal Street club where big names drop in unannounced.',
    tags: ['comedy'],
  },
  {
    id: 'evt-bowery',
    name: 'Indie Show at Bowery Ballroom',
    kind: 'event',
    neighborhood: 'Lower East Side',
    priceTier: 2,
    startTime: '20:30',
    endTime: '23:00',
    lat: 40.7204,
    lng: -73.9937,
    address: '6 Delancey St, New York, NY',
    bookingUrl: 'https://www.boweryballroom.com/',
    description: 'Beloved 575-cap room with balcony views and a knack for great bookings.',
    tags: ['live music'],
  },
  {
    id: 'evt-brooklyn-bowl',
    name: 'Late Set at Brooklyn Bowl',
    kind: 'event',
    neighborhood: 'Williamsburg',
    priceTier: 2,
    startTime: '21:00',
    endTime: '23:30',
    lat: 40.7219,
    lng: -73.9576,
    address: '61 Wythe Ave, Brooklyn, NY',
    bookingUrl: 'https://www.brooklynbowl.com/',
    description: 'Bowling lanes, fried chicken, and a serious stage under one Williamsburg roof.',
    tags: ['live music'],
  },
  {
    id: 'evt-film-forum',
    name: 'Repertory Film at Film Forum',
    kind: 'event',
    neighborhood: 'SoHo',
    priceTier: 2,
    startTime: '19:00',
    endTime: '21:00',
    lat: 40.7301,
    lng: -74.0048,
    address: '209 W Houston St, New York, NY',
    bookingUrl: 'https://filmforum.org/',
    description: 'Nonprofit cinema on Houston Street known for sharp repertory programming.',
    tags: ['film', 'art'],
  },
  {
    id: 'evt-highline-art',
    name: 'High Line Art Walk',
    kind: 'activity',
    neighborhood: 'Chelsea',
    priceTier: 1,
    startTime: '18:00',
    endTime: '19:30',
    lat: 40.748,
    lng: -74.0048,
    address: 'The High Line, New York, NY',
    bookingUrl: 'https://www.thehighline.org/',
    description: 'Elevated park with rotating public art and Hudson views, best near golden hour.',
    tags: ['outdoors', 'art', 'walk'],
  },
  {
    id: 'evt-mercury',
    name: 'Showcase at Mercury Lounge',
    kind: 'event',
    neighborhood: 'Lower East Side',
    priceTier: 2,
    startTime: '19:30',
    endTime: '21:30',
    lat: 40.7223,
    lng: -73.9874,
    address: '217 E Houston St, New York, NY',
    bookingUrl: 'https://www.mercuryloungenyc.com/',
    description: 'Tiny LES rock room where breakout acts play before the big stages.',
    tags: ['live music'],
  },
  // ---- Daytime activities (flexible timing; fill morning/afternoon windows) --
  {
    id: 'act-whitney',
    name: 'Whitney Museum of American Art',
    kind: 'activity',
    neighborhood: 'Chelsea',
    priceTier: 2,
    durationMin: 120,
    lat: 40.7396,
    lng: -74.0089,
    address: '99 Gansevoort St, New York, NY',
    bookingUrl: 'https://whitney.org/',
    description: 'American art in a Renzo Piano building with terraces over the High Line.',
    tags: ['art'],
  },
  {
    id: 'act-highline-day',
    name: 'Walk the High Line',
    kind: 'activity',
    neighborhood: 'Chelsea',
    priceTier: 1,
    durationMin: 60,
    lat: 40.748,
    lng: -74.0048,
    address: 'The High Line, New York, NY',
    bookingUrl: 'https://www.thehighline.org/',
    description: 'A 1.5 mile stroll on the old rail line from Gansevoort to Hudson Yards.',
    tags: ['outdoors', 'walk', 'art'],
  },
  {
    id: 'act-washington-sq',
    name: 'Washington Square Park',
    kind: 'activity',
    neighborhood: 'West Village',
    priceTier: 1,
    durationMin: 45,
    lat: 40.7308,
    lng: -73.9973,
    address: 'Washington Square Park, New York, NY',
    description: 'The Village living room: buskers, chess hustlers, and the arch.',
    tags: ['outdoors', 'walk'],
  },
  {
    id: 'act-tenement',
    name: 'Tenement Museum Tour',
    kind: 'activity',
    neighborhood: 'Lower East Side',
    priceTier: 2,
    durationMin: 75,
    lat: 40.7188,
    lng: -73.99,
    address: '103 Orchard St, New York, NY',
    bookingUrl: 'https://www.tenement.org/',
    description: 'Guided tours through preserved immigrant apartments on Orchard Street.',
    tags: ['art', 'walk'],
  },
  {
    id: 'act-brooklyn-bridge-park',
    name: 'Brooklyn Bridge Park and Jane’s Carousel',
    kind: 'activity',
    neighborhood: 'DUMBO',
    priceTier: 1,
    durationMin: 75,
    lat: 40.7024,
    lng: -73.9959,
    address: 'Brooklyn Bridge Park, Brooklyn, NY',
    description: 'Waterfront lawns and a restored 1922 carousel under the bridge.',
    tags: ['outdoors', 'walk'],
  },
  {
    id: 'act-bushwick-collective',
    name: 'Bushwick Collective Street Art',
    kind: 'activity',
    neighborhood: 'Bushwick',
    priceTier: 1,
    durationMin: 60,
    lat: 40.7057,
    lng: -73.9235,
    address: 'Troutman St & St Nicholas Ave, Brooklyn, NY',
    description: 'Blocks of large-scale murals from a rotating cast of street artists.',
    tags: ['art', 'walk', 'outdoors'],
  },
  {
    id: 'act-moving-image',
    name: 'Museum of the Moving Image',
    kind: 'activity',
    neighborhood: 'Astoria',
    priceTier: 2,
    durationMin: 90,
    lat: 40.7565,
    lng: -73.9242,
    address: '36-01 35th Ave, Astoria, NY',
    bookingUrl: 'https://movingimage.org/',
    description: 'Film and TV history in Astoria, from Muppets to movie cameras.',
    tags: ['film', 'art'],
  },
  {
    id: 'act-apollo',
    name: 'Apollo Theater Walk and Harlem Stroll',
    kind: 'activity',
    neighborhood: 'Harlem',
    priceTier: 1,
    durationMin: 60,
    lat: 40.8099,
    lng: -73.9503,
    address: '253 W 125th St, New York, NY',
    description: 'Walk 125th Street past the Apollo marquee and Harlem landmarks.',
    tags: ['walk', 'live music'],
  },
  {
    id: 'act-battery-ferry',
    name: 'Staten Island Ferry and Battery Park',
    kind: 'activity',
    neighborhood: 'Financial District',
    priceTier: 1,
    durationMin: 75,
    lat: 40.7013,
    lng: -74.0134,
    address: 'Whitehall Terminal, New York, NY',
    description: 'A free harbor crossing with Statue of Liberty views, then the Battery.',
    tags: ['outdoors', 'walk'],
  },
  {
    id: 'act-transmitter-park',
    name: 'Transmitter Park and Greenpoint Waterfront',
    kind: 'activity',
    neighborhood: 'Greenpoint',
    priceTier: 1,
    durationMin: 45,
    lat: 40.7305,
    lng: -73.9585,
    address: 'WNW Transmitter Park, Brooklyn, NY',
    description: 'Small waterfront park with a straight shot view of the midtown skyline.',
    tags: ['outdoors', 'walk'],
  },
  {
    id: 'act-soho-galleries',
    name: 'SoHo Galleries and Shopping Stroll',
    kind: 'activity',
    neighborhood: 'SoHo',
    priceTier: 2,
    durationMin: 60,
    lat: 40.7233,
    lng: -74.0011,
    address: 'Broadway & Prince St, New York, NY',
    description: 'Cast-iron blocks of galleries and flagships between Houston and Canal.',
    tags: ['art', 'walk'],
  },
  // ---- Fixed-time daytime events ------------------------------------------
  {
    id: 'evt-film-matinee',
    name: 'Matinee at Film Forum',
    kind: 'event',
    neighborhood: 'SoHo',
    priceTier: 2,
    startTime: '13:30',
    endTime: '15:30',
    lat: 40.7301,
    lng: -74.0048,
    address: '209 W Houston St, New York, NY',
    bookingUrl: 'https://filmforum.org/',
    description: 'An afternoon repertory screening at the Houston Street nonprofit cinema.',
    tags: ['film', 'art'],
  },
  {
    id: 'evt-brooklyn-flea',
    name: 'Brooklyn Flea Market',
    kind: 'activity',
    neighborhood: 'DUMBO',
    priceTier: 1,
    startTime: '10:00',
    endTime: '17:00',
    lat: 40.7033,
    lng: -73.9903,
    address: '80 Pearl St, Brooklyn, NY',
    description: 'Weekend market of vintage, records, and local makers under the arches.',
    tags: ['outdoors', 'walk'],
  },
];

/** Curated NYC seed places (restaurants + bars; flexible timing). */
export const SEED_PLACES: Candidate[] = [
  {
    id: 'plc-via-carota',
    name: 'Via Carota',
    kind: 'restaurant',
    neighborhood: 'West Village',
    priceTier: 3,
    durationMin: 90,
    lat: 40.7338,
    lng: -74.0027,
    address: '51 Grove St, New York, NY',
    description: 'The Village trattoria everyone loves; go early for the svizzerina.',
    tags: ['food'],
  },
  {
    id: 'plc-joes-pizza',
    name: "Joe's Pizza",
    kind: 'restaurant',
    neighborhood: 'West Village',
    priceTier: 1,
    durationMin: 30,
    lat: 40.7305,
    lng: -74.0023,
    address: '7 Carmine St, New York, NY',
    description: 'The benchmark New York slice, folded and eaten standing up.',
    tags: ['food', 'late-night'],
  },
  {
    id: 'plc-katz',
    name: "Katz's Delicatessen",
    kind: 'restaurant',
    neighborhood: 'Lower East Side',
    priceTier: 2,
    durationMin: 60,
    lat: 40.7223,
    lng: -73.9874,
    address: '205 E Houston St, New York, NY',
    description: 'Pastrami on rye at the 1888 deli; take a ticket and do not lose it.',
    tags: ['food'],
  },
  {
    id: 'plc-ramen',
    name: 'Ippudo NY',
    kind: 'restaurant',
    neighborhood: 'East Village',
    priceTier: 2,
    durationMin: 60,
    lat: 40.7307,
    lng: -73.9903,
    address: '65 4th Ave, New York, NY',
    description: 'Tonkotsu ramen with a rowdy irasshaimase welcome; expect a wait.',
    tags: ['food', 'late-night'],
  },
  {
    id: 'plc-slice-1',
    name: 'Artichoke Basille',
    kind: 'restaurant',
    neighborhood: 'East Village',
    priceTier: 1,
    durationMin: 30,
    lat: 40.7322,
    lng: -73.9866,
    address: '321 E 14th St, New York, NY',
    description: 'The famously heavy artichoke slice, best after a show.',
    tags: ['food', 'late-night'],
  },
  {
    id: 'plc-attaboy',
    name: 'Attaboy',
    kind: 'bar',
    neighborhood: 'Lower East Side',
    priceTier: 3,
    durationMin: 75,
    lat: 40.7184,
    lng: -73.9916,
    address: '134 Eldridge St, New York, NY',
    description: 'No-menu cocktails behind an unmarked Eldridge Street door.',
    tags: ['bar'],
  },
  {
    id: 'plc-employees-only',
    name: 'Employees Only',
    kind: 'bar',
    neighborhood: 'West Village',
    priceTier: 3,
    durationMin: 75,
    lat: 40.7333,
    lng: -74.0061,
    address: '510 Hudson St, New York, NY',
    description: 'Speakeasy-style West Village institution with late kitchen hours.',
    tags: ['bar'],
  },
  {
    id: 'plc-westlight',
    name: 'Westlight',
    kind: 'bar',
    neighborhood: 'Williamsburg',
    priceTier: 3,
    durationMin: 75,
    lat: 40.7223,
    lng: -73.9573,
    address: '111 N 12th St, Brooklyn, NY',
    description: '22nd-floor rooftop bar with a full sweep of the Manhattan skyline.',
    tags: ['bar', 'rooftop'],
  },
  {
    id: 'plc-llama-inn',
    name: 'Llama Inn',
    kind: 'restaurant',
    neighborhood: 'Williamsburg',
    priceTier: 3,
    durationMin: 90,
    lat: 40.7186,
    lng: -73.9609,
    address: '50 Withers St, Brooklyn, NY',
    description: 'Inventive Peruvian under the BQE; the beef tenderloin skewers travel far.',
    tags: ['food'],
  },
  {
    id: 'plc-balthazar',
    name: 'Balthazar',
    kind: 'restaurant',
    neighborhood: 'SoHo',
    priceTier: 3,
    durationMin: 90,
    lat: 40.7224,
    lng: -73.9982,
    address: '80 Spring St, New York, NY',
    description: 'The grand SoHo brasserie; steak frites and people-watching since 1997.',
    tags: ['food', 'brunch'],
  },
  {
    id: 'plc-time-out',
    name: 'Time Out Market',
    kind: 'restaurant',
    neighborhood: 'DUMBO',
    priceTier: 2,
    durationMin: 60,
    lat: 40.7025,
    lng: -73.9903,
    address: '55 Water St, Brooklyn, NY',
    description: 'DUMBO food hall with rooftop seating and skyline views.',
    tags: ['food'],
  },
  {
    id: 'plc-dead-rabbit',
    name: 'The Dead Rabbit',
    kind: 'bar',
    neighborhood: 'Financial District',
    priceTier: 3,
    durationMin: 75,
    lat: 40.7033,
    lng: -74.0114,
    address: '30 Water St, New York, NY',
    description: 'Award-winning Irish pub on Water Street; sawdust downstairs, cocktails up.',
    tags: ['bar'],
  },
  // ---- Broader neighborhood coverage + daytime brunch/coffee ---------------
  {
    id: 'plc-chelsea-market',
    name: 'Chelsea Market',
    kind: 'restaurant',
    neighborhood: 'Chelsea',
    priceTier: 2,
    durationMin: 60,
    lat: 40.742,
    lng: -74.0061,
    address: '75 9th Ave, New York, NY',
    description: 'Indoor market in the old Nabisco factory; tacos, lobster, and more.',
    tags: ['food'],
  },
  {
    id: 'plc-jacks-wife-freda',
    name: 'Jack’s Wife Freda',
    kind: 'restaurant',
    neighborhood: 'SoHo',
    priceTier: 2,
    durationMin: 75,
    lat: 40.7228,
    lng: -73.9985,
    address: '224 Lafayette St, New York, NY',
    description: 'Mediterranean-ish all-day cafe beloved for green shakshuka at brunch.',
    tags: ['food', 'brunch'],
  },
  {
    id: 'plc-buvette',
    name: 'Buvette',
    kind: 'restaurant',
    neighborhood: 'West Village',
    priceTier: 2,
    durationMin: 75,
    lat: 40.7333,
    lng: -74.0037,
    address: '42 Grove St, New York, NY',
    description: 'Tiny Grove Street gastrotheque; steamed eggs in the morning, wine at night.',
    tags: ['food', 'brunch'],
  },
  {
    id: 'plc-grimaldis',
    name: 'Grimaldi’s Pizzeria',
    kind: 'restaurant',
    neighborhood: 'DUMBO',
    priceTier: 2,
    durationMin: 60,
    lat: 40.7024,
    lng: -73.9932,
    address: '1 Front St, Brooklyn, NY',
    description: 'Coal-oven pies under the Brooklyn Bridge; the line moves fast.',
    tags: ['food'],
  },
  {
    id: 'plc-red-rooster',
    name: 'Red Rooster Harlem',
    kind: 'restaurant',
    neighborhood: 'Harlem',
    priceTier: 3,
    durationMin: 90,
    lat: 40.8085,
    lng: -73.9454,
    address: '310 Lenox Ave, New York, NY',
    description: 'Marcus Samuelsson’s Lenox Avenue dining room with live music downstairs.',
    tags: ['food', 'live music'],
  },
  {
    id: 'plc-sylvias',
    name: 'Sylvia’s',
    kind: 'restaurant',
    neighborhood: 'Harlem',
    priceTier: 2,
    durationMin: 75,
    lat: 40.8082,
    lng: -73.9442,
    address: '328 Malcolm X Blvd, New York, NY',
    description: 'Harlem’s queen of soul food since 1962; go for the fried chicken.',
    tags: ['food', 'brunch'],
  },
  {
    id: 'plc-taverna-kyclades',
    name: 'Taverna Kyclades',
    kind: 'restaurant',
    neighborhood: 'Astoria',
    priceTier: 2,
    durationMin: 90,
    lat: 40.7739,
    lng: -73.9109,
    address: '33-07 Ditmars Blvd, Astoria, NY',
    description: 'Astoria Greek seafood standby; the grilled octopus earns the wait.',
    tags: ['food'],
  },
  {
    id: 'plc-bohemian-hall',
    name: 'Bohemian Hall Beer Garden',
    kind: 'bar',
    neighborhood: 'Astoria',
    priceTier: 2,
    durationMin: 90,
    lat: 40.7702,
    lng: -73.9146,
    address: '29-19 24th Ave, Astoria, NY',
    description: 'Czech beer garden from 1910 with long tables under the trees.',
    tags: ['bar', 'outdoors'],
  },
  {
    id: 'plc-robertas',
    name: 'Roberta’s',
    kind: 'restaurant',
    neighborhood: 'Bushwick',
    priceTier: 2,
    durationMin: 90,
    lat: 40.705,
    lng: -73.9337,
    address: '261 Moore St, Brooklyn, NY',
    description: 'The Bushwick pizza pioneer with a tiki backyard and wood-fired pies.',
    tags: ['food'],
  },
  {
    id: 'plc-house-of-yes',
    name: 'House of Yes',
    kind: 'bar',
    neighborhood: 'Bushwick',
    priceTier: 2,
    durationMin: 90,
    lat: 40.7069,
    lng: -73.9233,
    address: '2 Wyckoff Ave, Brooklyn, NY',
    bookingUrl: 'https://houseofyes.org/',
    description: 'Circus-meets-nightclub warehouse; themed nights and aerialists.',
    tags: ['bar', 'live music'],
  },
  {
    id: 'plc-paulie-gees',
    name: 'Paulie Gee’s',
    kind: 'restaurant',
    neighborhood: 'Greenpoint',
    priceTier: 2,
    durationMin: 75,
    lat: 40.7296,
    lng: -73.9585,
    address: '60 Greenpoint Ave, Brooklyn, NY',
    description: 'Wood-fired Greenpoint pizza den famous for the hot-honey Hellboy.',
    tags: ['food'],
  },
  {
    id: 'plc-peter-pan',
    name: 'Peter Pan Donut & Pastry',
    kind: 'restaurant',
    neighborhood: 'Greenpoint',
    priceTier: 1,
    durationMin: 30,
    lat: 40.7241,
    lng: -73.9509,
    address: '727 Manhattan Ave, Brooklyn, NY',
    description: 'Old-school Greenpoint donut counter; get the red velvet early.',
    tags: ['food', 'coffee'],
  },
  {
    id: 'plc-abraco',
    name: 'Abraço Coffee',
    kind: 'restaurant',
    neighborhood: 'East Village',
    priceTier: 1,
    durationMin: 30,
    lat: 40.7273,
    lng: -73.9852,
    address: '81 E 7th St, New York, NY',
    description: 'Espresso and olive oil cake at a tiny East 7th Street counter.',
    tags: ['food', 'coffee'],
  },
];

/** Storage namespace prefix. */
export const STORAGE_PREFIX = 'outnyc:v1:';
