// =============================================================================
// OutNYC — NYC seed data (lib/constants.ts)
// =============================================================================
// The mock/seed dataset that powers the entire zero-key experience.
//   - SEED_PROFILE mirrors the profile seed in supabase/migrations/0001_init.sql
//   - BUCKET_SEED  mirrors the bucket_list seed in the same migration
//   - SEED_EVENTS / SEED_PLACES feed the heuristic planner and providers
// Keep BUCKET_SEED and SEED_PROFILE in sync with the SQL seed.
// =============================================================================

import type { BucketItem, Candidate, Profile } from './types';

export const NEIGHBORHOODS: string[] = [
  'West Village',
  'East Village',
  'Lower East Side',
  'Williamsburg',
  'Chelsea',
  'SoHo',
  'Greenpoint',
  'DUMBO',
  'Financial District',
  'Harlem',
  'Astoria',
  'Bushwick',
];

export const INTEREST_TAGS: string[] = [
  'live music',
  'food',
  'art',
  'outdoors',
  'bar',
  'comedy',
  'film',
  'walk',
];

/** Single-user profile seed. Mirrors the SQL profile insert. */
export const SEED_PROFILE: Profile = {
  displayName: 'You',
  partySize: 2,
  defaultNeighborhoods: ['West Village', 'Lower East Side', 'Williamsburg'],
  priceRange: { min: 1, max: 3 },
  interests: ['live music', 'food', 'art', 'outdoors'],
  homeBase: 'West Village',
  onboarded: false,
};

/** Bucket-list seed. Mirrors BUCKET_SEED in 0001_init.sql (same order + fields). */
export const BUCKET_SEED: BucketItem[] = [
  {
    id: 'seed-bucket-0',
    title: 'Catch sunset on the High Line',
    note: 'Best near sunset; walk the whole stretch.',
    neighborhood: 'Chelsea',
    priceTier: 1,
    tags: ['outdoors', 'walk'],
    done: false,
    sortOrder: 0,
  },
  {
    id: 'seed-bucket-1',
    title: 'Jazz set at the Village Vanguard',
    note: 'Reserve ahead; iconic basement room.',
    neighborhood: 'West Village',
    priceTier: 3,
    tags: ['live music'],
    done: false,
    sortOrder: 1,
  },
  {
    id: 'seed-bucket-2',
    title: 'Slice crawl through the East Village',
    note: 'Hit three classic spots in one night.',
    neighborhood: 'East Village',
    priceTier: 1,
    tags: ['food'],
    done: false,
    sortOrder: 2,
  },
  {
    id: 'seed-bucket-3',
    title: 'Smorgasburg on a Saturday',
    note: 'Go hungry; cash + card.',
    neighborhood: 'Williamsburg',
    priceTier: 2,
    tags: ['food', 'outdoors'],
    done: false,
    sortOrder: 3,
  },
  {
    id: 'seed-bucket-4',
    title: 'Late-night ramen in the East Village',
    note: 'For after a show.',
    neighborhood: 'East Village',
    priceTier: 2,
    tags: ['food'],
    done: false,
    sortOrder: 4,
  },
  {
    id: 'seed-bucket-5',
    title: 'Rooftop drinks in Lower Manhattan',
    note: 'Sunset views over the harbor.',
    neighborhood: 'Financial District',
    priceTier: 3,
    tags: ['bar'],
    done: false,
    sortOrder: 5,
  },
  {
    id: 'seed-bucket-6',
    title: 'Brooklyn Bridge walk at golden hour',
    note: 'Start Manhattan side, end in DUMBO.',
    neighborhood: 'DUMBO',
    priceTier: 1,
    tags: ['outdoors', 'walk'],
    done: false,
    sortOrder: 6,
  },
  {
    id: 'seed-bucket-7',
    title: 'See a show at the Comedy Cellar',
    note: 'Standby line moves fast on weeknights.',
    neighborhood: 'West Village',
    priceTier: 2,
    tags: ['comedy'],
    done: false,
    sortOrder: 7,
  },
];

/** Curated NYC seed events (have fixed start/end times). */
export const SEED_EVENTS: Candidate[] = [
  {
    id: 'evt-vanguard',
    name: 'Live Jazz — Village Vanguard',
    kind: 'event',
    neighborhood: 'West Village',
    priceTier: 3,
    startTime: '20:00',
    endTime: '22:00',
    lat: 40.7359,
    lng: -74.0008,
    address: '178 7th Ave S, New York, NY',
    bookingUrl: 'https://villagevanguard.com/',
    tags: ['live music'],
  },
  {
    id: 'evt-comedy-cellar',
    name: 'Stand-up — Comedy Cellar',
    kind: 'event',
    neighborhood: 'West Village',
    priceTier: 2,
    startTime: '21:00',
    endTime: '22:30',
    lat: 40.7301,
    lng: -74.0007,
    address: '117 MacDougal St, New York, NY',
    bookingUrl: 'https://www.comedycellar.com/',
    tags: ['comedy'],
  },
  {
    id: 'evt-bowery',
    name: 'Indie Show — Bowery Ballroom',
    kind: 'event',
    neighborhood: 'Lower East Side',
    priceTier: 2,
    startTime: '20:30',
    endTime: '23:00',
    lat: 40.7204,
    lng: -73.9937,
    address: '6 Delancey St, New York, NY',
    bookingUrl: 'https://www.boweryballroom.com/',
    tags: ['live music'],
  },
  {
    id: 'evt-brooklyn-bowl',
    name: 'Late Set — Brooklyn Bowl',
    kind: 'event',
    neighborhood: 'Williamsburg',
    priceTier: 2,
    startTime: '21:00',
    endTime: '23:30',
    lat: 40.7219,
    lng: -73.9576,
    address: '61 Wythe Ave, Brooklyn, NY',
    bookingUrl: 'https://www.brooklynbowl.com/',
    tags: ['live music'],
  },
  {
    id: 'evt-film-forum',
    name: 'Repertory Film — Film Forum',
    kind: 'event',
    neighborhood: 'SoHo',
    priceTier: 2,
    startTime: '19:00',
    endTime: '21:00',
    lat: 40.7301,
    lng: -74.0048,
    address: '209 W Houston St, New York, NY',
    bookingUrl: 'https://filmforum.org/',
    tags: ['film', 'art'],
  },
  {
    id: 'evt-highline-art',
    name: 'High Line Art Walk',
    kind: 'activity',
    neighborhood: 'Chelsea',
    priceTier: 1,
    startTime: '18:00',
    endTime: '19:30',
    lat: 40.748,
    lng: -74.0048,
    address: 'The High Line, New York, NY',
    bookingUrl: 'https://www.thehighline.org/',
    tags: ['outdoors', 'art', 'walk'],
  },
  {
    id: 'evt-mercury',
    name: 'Showcase — Mercury Lounge',
    kind: 'event',
    neighborhood: 'Lower East Side',
    priceTier: 2,
    startTime: '19:30',
    endTime: '21:30',
    lat: 40.7223,
    lng: -73.9874,
    address: '217 E Houston St, New York, NY',
    bookingUrl: 'https://www.mercuryloungenyc.com/',
    tags: ['live music'],
  },
];

/** Curated NYC seed places (restaurants + bars; flexible timing). */
export const SEED_PLACES: Candidate[] = [
  {
    id: 'plc-via-carota',
    name: 'Via Carota',
    kind: 'restaurant',
    neighborhood: 'West Village',
    priceTier: 3,
    durationMin: 90,
    lat: 40.7338,
    lng: -74.0027,
    address: '51 Grove St, New York, NY',
    tags: ['food'],
  },
  {
    id: 'plc-joes-pizza',
    name: "Joe's Pizza",
    kind: 'restaurant',
    neighborhood: 'West Village',
    priceTier: 1,
    durationMin: 30,
    lat: 40.7305,
    lng: -74.0023,
    address: '7 Carmine St, New York, NY',
    tags: ['food'],
  },
  {
    id: 'plc-katz',
    name: "Katz's Delicatessen",
    kind: 'restaurant',
    neighborhood: 'Lower East Side',
    priceTier: 2,
    durationMin: 60,
    lat: 40.7223,
    lng: -73.9874,
    address: '205 E Houston St, New York, NY',
    tags: ['food'],
  },
  {
    id: 'plc-ramen',
    name: 'Ippudo NY',
    kind: 'restaurant',
    neighborhood: 'East Village',
    priceTier: 2,
    durationMin: 60,
    lat: 40.7307,
    lng: -73.9903,
    address: '65 4th Ave, New York, NY',
    tags: ['food'],
  },
  {
    id: 'plc-slice-1',
    name: 'Artichoke Basille',
    kind: 'restaurant',
    neighborhood: 'East Village',
    priceTier: 1,
    durationMin: 30,
    lat: 40.7322,
    lng: -73.9866,
    address: '321 E 14th St, New York, NY',
    tags: ['food'],
  },
  {
    id: 'plc-attaboy',
    name: 'Attaboy',
    kind: 'bar',
    neighborhood: 'Lower East Side',
    priceTier: 3,
    durationMin: 75,
    lat: 40.7184,
    lng: -73.9916,
    address: '134 Eldridge St, New York, NY',
    tags: ['bar'],
  },
  {
    id: 'plc-employees-only',
    name: 'Employees Only',
    kind: 'bar',
    neighborhood: 'West Village',
    priceTier: 3,
    durationMin: 75,
    lat: 40.7333,
    lng: -74.0061,
    address: '510 Hudson St, New York, NY',
    tags: ['bar'],
  },
  {
    id: 'plc-westlight',
    name: 'Westlight (Rooftop)',
    kind: 'bar',
    neighborhood: 'Williamsburg',
    priceTier: 3,
    durationMin: 75,
    lat: 40.7223,
    lng: -73.9573,
    address: '111 N 12th St, Brooklyn, NY',
    tags: ['bar'],
  },
  {
    id: 'plc-llama-inn',
    name: 'Llama Inn',
    kind: 'restaurant',
    neighborhood: 'Williamsburg',
    priceTier: 3,
    durationMin: 90,
    lat: 40.7186,
    lng: -73.9609,
    address: '50 Withers St, Brooklyn, NY',
    tags: ['food'],
  },
  {
    id: 'plc-balthazar',
    name: 'Balthazar',
    kind: 'restaurant',
    neighborhood: 'SoHo',
    priceTier: 3,
    durationMin: 90,
    lat: 40.7224,
    lng: -73.9982,
    address: '80 Spring St, New York, NY',
    tags: ['food'],
  },
  {
    id: 'plc-time-out',
    name: 'Time Out Market (DUMBO)',
    kind: 'restaurant',
    neighborhood: 'DUMBO',
    priceTier: 2,
    durationMin: 60,
    lat: 40.7025,
    lng: -73.9903,
    address: '55 Water St, Brooklyn, NY',
    tags: ['food'],
  },
  {
    id: 'plc-dead-rabbit',
    name: 'The Dead Rabbit',
    kind: 'bar',
    neighborhood: 'Financial District',
    priceTier: 3,
    durationMin: 75,
    lat: 40.7033,
    lng: -74.0114,
    address: '30 Water St, New York, NY',
    tags: ['bar'],
  },
];

/** Storage namespace prefix. */
export const STORAGE_PREFIX = 'outnyc:v1:';
