// =============================================================================
// OutNYC: NYC seed data (lib/constants.ts)
// =============================================================================
// The curated NYC guide that powers the zero-key experience.
//   - SEED_PROFILE mirrors the profile seed in supabase/migrations/0001_init.sql
//   - BUCKET_SEED  mirrors the bucket_list seed in the same migration
//   - SEED_EVENTS / SEED_PLACES feed the heuristic planner and providers
// Timing tags the planner understands: 'coffee', 'brunch', 'late-night',
// 'rooftop'. Keep BUCKET_SEED and SEED_PROFILE in sync with the SQL seed.
// =============================================================================

import { CATALOG_EVENTS, CATALOG_PLACES } from './catalog';
import type { BucketItem, Candidate, PriceTier, Profile } from './types';

export const NEIGHBORHOODS = [
  'West Village',
  'East Village',
  'Lower East Side',
  'Williamsburg',
  'Chelsea',
  'SoHo',
  'Nolita',
  'Chinatown',
  'Tribeca',
  'Greenpoint',
  'DUMBO',
  'Financial District',
  'Midtown',
  'Upper East Side',
  'Upper West Side',
  'Harlem',
  'Astoria',
  'Long Island City',
  'Bushwick',
  'Park Slope',
] as const;

export type Neighborhood = (typeof NEIGHBORHOODS)[number];

export const PRICE_TIERS: PriceTier[] = [1, 2, 3, 4];

export const INTEREST_TAGS: string[] = [
  'live music',
  'food',
  'art',
  'outdoors',
  'bar',
  'comedy',
  'film',
  'walk',
];

/** Single-user profile seed. Mirrors the SQL profile insert. */
export const SEED_PROFILE: Profile = {
  displayName: 'You',
  partySize: 2,
  defaultNeighborhoods: ['West Village', 'Lower East Side', 'Williamsburg'],
  priceRange: { min: 1, max: 3 },
  interests: ['live music', 'food', 'art', 'outdoors'],
  homeBase: 'West Village',
  onboarded: false,
};

/** Bucket-list seed. Mirrors BUCKET_SEED in 0001_init.sql (same order + fields).
 *  Notes are written for someone who has never heard of the place: what it IS,
 *  then how to do it right. Plain punctuation only (no em dashes anywhere). */
export const BUCKET_SEED: BucketItem[] = [
  {
    id: 'seed-bucket-0',
    title: 'Sunset at the High Line',
    note: 'An elevated park built on an old freight rail line, 30 feet above the west side streets. Enter at Gansevoort St and walk the planted mile and a half north as the sun drops over the Hudson.',
    neighborhood: 'Chelsea',
    priceTier: 1,
    tags: ['outdoors', 'walk'],
    done: false,
    sortOrder: 0,
  },
  {
    id: 'seed-bucket-1',
    title: 'Jazz set at the Village Vanguard',
    note: 'The most famous basement jazz club in the world, a tiny wedge-shaped room open since 1935. Every jazz great has played it. Two sets a night; reserve ahead.',
    neighborhood: 'West Village',
    priceTier: 3,
    tags: ['live music'],
    done: false,
    sortOrder: 1,
  },
  {
    id: 'seed-bucket-2',
    title: 'Slice crawl: 2 Bros, Stromboli, then Artichoke',
    note: 'Three famous East Village pizza counters within a 15 minute walk of each other: a one dollar-ish thin slice, a corner-shop classic, and a thick slice smothered in artichoke cream. One slice at each.',
    neighborhood: 'East Village',
    priceTier: 1,
    tags: ['food'],
    done: false,
    sortOrder: 2,
  },
  {
    id: 'seed-bucket-3',
    title: 'Smorgasburg on a Saturday',
    note: 'A huge open-air food market on the Williamsburg waterfront, every Saturday: dozens of vendors selling one famous thing each, with the Manhattan skyline across the river. Go hungry.',
    neighborhood: 'Williamsburg',
    priceTier: 2,
    tags: ['food', 'outdoors'],
    done: false,
    sortOrder: 3,
  },
  {
    id: 'seed-bucket-4',
    title: 'Late-night ramen at Ippudo',
    note: 'The New York outpost of a famous Japanese ramen house: rich pork-broth noodle bowls, a shouted welcome when you walk in, and a kitchen that runs late. Perfect after a show.',
    neighborhood: 'East Village',
    priceTier: 2,
    tags: ['food', 'late-night'],
    done: false,
    sortOrder: 4,
  },
  {
    id: 'seed-bucket-5',
    title: 'Rooftop drinks at Overstory',
    note: 'A small cocktail bar wrapped around the 64th floor of a downtown tower, with open-air views over the harbor and the bridges. Go near sunset and reserve ahead.',
    neighborhood: 'Financial District',
    priceTier: 3,
    tags: ['bar', 'rooftop'],
    done: false,
    sortOrder: 5,
  },
  {
    id: 'seed-bucket-6',
    title: 'Brooklyn Bridge walk at golden hour',
    note: 'The classic walk across the 1883 bridge on its raised wooden promenade, with the skyline behind you and the harbor below. Start at City Hall in Manhattan and come down in DUMBO for the photo everyone takes.',
    neighborhood: 'DUMBO',
    priceTier: 1,
    tags: ['outdoors', 'walk'],
    done: false,
    sortOrder: 6,
  },
  {
    id: 'seed-bucket-7',
    title: 'See a show at the Comedy Cellar',
    note: 'A low-ceilinged Greenwich Village basement that is the most famous stand-up room in America. Big names drop in unannounced. The standby line moves fast on weeknights.',
    neighborhood: 'West Village',
    priceTier: 2,
    tags: ['comedy'],
    done: false,
    sortOrder: 7,
  },
];

/** Curated NYC seed events + activities. The original hand-picked core lives
 *  here; the generated area catalogs (lib/catalog) are folded in at the bottom
 *  of this file, taking the pool from ~45 to ~450 venues. */
const CORE_EVENTS: Candidate[] = [
  {
    id: 'evt-vanguard',
    name: 'Live Jazz at the Village Vanguard',
    kind: 'event',
    neighborhood: 'West Village',
    priceTier: 3,
    startTime: '20:00',
    endTime: '22:00',
    lat: 40.7359,
    lng: -74.0008,
    address: '178 7th Ave S, New York, NY',
    bookingUrl: 'https://villagevanguard.com/',
    description: 'Jazz club: the most storied basement listening room in the city, running since 1935.',
    tags: ['live music'],
  },
  {
    id: 'evt-comedy-cellar',
    name: 'Stand-up at the Comedy Cellar',
    kind: 'event',
    neighborhood: 'West Village',
    priceTier: 2,
    startTime: '21:00',
    endTime: '22:30',
    lat: 40.7301,
    lng: -74.0007,
    address: '117 MacDougal St, New York, NY',
    bookingUrl: 'https://www.comedycellar.com/',
    description: 'Comedy club: low-ceilinged stand-up room where big names drop in unannounced.',
    tags: ['comedy'],
  },
  {
    id: 'evt-bowery',
    name: 'Indie Show at Bowery Ballroom',
    kind: 'event',
    neighborhood: 'Lower East Side',
    priceTier: 2,
    startTime: '20:30',
    endTime: '23:00',
    lat: 40.7204,
    lng: -73.9937,
    address: '6 Delancey St, New York, NY',
    bookingUrl: 'https://www.boweryballroom.com/',
    description: 'Live-music venue: beloved 575-person room with balcony views and sharp bookings.',
    tags: ['live music'],
  },
  {
    id: 'evt-brooklyn-bowl',
    name: 'Late Set at Brooklyn Bowl',
    kind: 'event',
    neighborhood: 'Williamsburg',
    priceTier: 2,
    startTime: '21:00',
    endTime: '23:30',
    lat: 40.7219,
    lng: -73.9576,
    address: '61 Wythe Ave, Brooklyn, NY',
    bookingUrl: 'https://www.brooklynbowl.com/',
    description: 'Live-music venue and bowling alley: lanes, fried chicken, and a serious stage.',
    tags: ['live music'],
  },
  {
    id: 'evt-film-forum',
    name: 'Repertory Film at Film Forum',
    kind: 'event',
    neighborhood: 'SoHo',
    priceTier: 2,
    startTime: '19:00',
    endTime: '21:00',
    lat: 40.7301,
    lng: -74.0048,
    address: '209 W Houston St, New York, NY',
    bookingUrl: 'https://filmforum.org/',
    description: 'Independent movie theater: nonprofit cinema for classic and new art films.',
    tags: ['film', 'art'],
  },
  {
    id: 'evt-highline-art',
    name: 'Art walk at the High Line',
    kind: 'activity',
    neighborhood: 'Chelsea',
    priceTier: 1,
    startTime: '18:00',
    endTime: '19:30',
    lat: 40.748,
    lng: -74.0048,
    address: 'The High Line, New York, NY',
    bookingUrl: 'https://www.thehighline.org/',
    description: 'Outdoor art walk: elevated park with rotating public art and Hudson River views.',
    tags: ['outdoors', 'art', 'walk'],
  },
  {
    id: 'evt-mercury',
    name: 'Showcase at Mercury Lounge',
    kind: 'event',
    neighborhood: 'Lower East Side',
    priceTier: 2,
    startTime: '19:30',
    endTime: '21:30',
    lat: 40.7223,
    lng: -73.9874,
    address: '217 E Houston St, New York, NY',
    bookingUrl: 'https://www.mercuryloungenyc.com/',
    description: 'Small live-music club: tiny rock room where breakout acts play first.',
    tags: ['live music'],
  },
  // ---- Daytime activities (flexible timing; fill morning/afternoon windows) --
  // (The Whitney lives in lib/catalog/downtown.ts as dt-whitney-museum.)
  {
    id: 'act-highline-day',
    name: 'Elevated park walk at the High Line',
    kind: 'activity',
    neighborhood: 'Chelsea',
    priceTier: 1,
    durationMin: 60,
    lat: 40.748,
    lng: -74.0048,
    address: 'The High Line, New York, NY',
    bookingUrl: 'https://www.thehighline.org/',
    description: 'Elevated park walk: 1.5 miles on an old rail line from the Village to Hudson Yards.',
    tags: ['outdoors', 'walk', 'art'],
  },
  {
    id: 'act-washington-sq',
    name: 'Washington Square Park',
    kind: 'activity',
    neighborhood: 'West Village',
    priceTier: 1,
    durationMin: 45,
    lat: 40.7308,
    lng: -73.9973,
    address: 'Washington Square Park, New York, NY',
    bookingUrl: 'https://www.nycgovparks.org/parks/washington-square-park',
    description: 'Public park: the Village living room: buskers, chess hustlers, and the marble arch.',
    tags: ['outdoors', 'walk'],
  },
  {
    id: 'act-tenement',
    name: 'Tenement Museum Tour',
    kind: 'activity',
    neighborhood: 'Lower East Side',
    priceTier: 2,
    durationMin: 75,
    lat: 40.7188,
    lng: -73.99,
    address: '103 Orchard St, New York, NY',
    bookingUrl: 'https://www.tenement.org/',
    description: 'History museum: guided tours through preserved 1800s immigrant apartments.',
    tags: ['art', 'walk'],
  },
  {
    id: 'act-brooklyn-bridge-park',
    name: 'Brooklyn Bridge Park and Jane’s Carousel',
    kind: 'activity',
    neighborhood: 'DUMBO',
    priceTier: 1,
    durationMin: 75,
    lat: 40.7024,
    lng: -73.9959,
    address: 'Brooklyn Bridge Park, Brooklyn, NY',
    bookingUrl: 'https://brooklynbridgepark.org/',
    description: 'Waterfront park: lawns, piers, and a restored 1922 carousel under the bridge.',
    tags: ['outdoors', 'walk'],
  },
  {
    id: 'act-bushwick-collective',
    name: 'Bushwick Collective Street Art',
    kind: 'activity',
    neighborhood: 'Bushwick',
    priceTier: 1,
    durationMin: 60,
    lat: 40.7057,
    lng: -73.9235,
    address: 'Troutman St & St Nicholas Ave, Brooklyn, NY',
    bookingUrl: 'http://thebushwickcollective.com/',
    description: 'Outdoor street-art gallery: blocks of large murals by a rotating cast of artists.',
    tags: ['art', 'walk', 'outdoors'],
  },
  {
    id: 'act-moving-image',
    name: 'Museum of the Moving Image',
    kind: 'activity',
    neighborhood: 'Astoria',
    priceTier: 2,
    durationMin: 90,
    lat: 40.7565,
    lng: -73.9242,
    address: '36-01 35th Ave, Astoria, NY',
    bookingUrl: 'https://movingimage.org/',
    description: 'Film and TV museum: screen history in Astoria, from Muppets to movie cameras.',
    tags: ['film', 'art'],
  },
  {
    id: 'act-apollo',
    name: 'Apollo Theater Walk and Harlem Stroll',
    kind: 'activity',
    neighborhood: 'Harlem',
    priceTier: 1,
    durationMin: 60,
    lat: 40.8099,
    lng: -73.9503,
    address: '253 W 125th St, New York, NY',
    bookingUrl: 'https://www.apollotheater.org/',
    description: 'Landmark walk: 125th Street past the Apollo Theater marquee and Harlem classics.',
    tags: ['walk', 'live music'],
  },
  {
    id: 'act-battery-ferry',
    name: 'Staten Island Ferry Ride',
    kind: 'activity',
    neighborhood: 'Financial District',
    priceTier: 1,
    durationMin: 75,
    lat: 40.7013,
    lng: -74.0134,
    address: 'Whitehall Terminal, New York, NY',
    bookingUrl: 'https://www.siferry.com/',
    description: 'Free harbor ferry ride: Statue of Liberty views, then a stroll in Battery Park.',
    tags: ['outdoors', 'walk'],
  },
  {
    id: 'act-transmitter-park',
    name: 'Transmitter Park and Greenpoint Waterfront',
    kind: 'activity',
    neighborhood: 'Greenpoint',
    priceTier: 1,
    durationMin: 45,
    lat: 40.7305,
    lng: -73.9585,
    address: 'WNW Transmitter Park, Brooklyn, NY',
    bookingUrl: 'https://www.nycgovparks.org/parks/transmitter-park',
    description: 'Small waterfront park: a lawn and pier with a straight-on midtown skyline view.',
    tags: ['outdoors', 'walk'],
  },
  {
    id: 'act-soho-galleries',
    name: 'SoHo Galleries and Shopping Stroll',
    kind: 'activity',
    neighborhood: 'SoHo',
    priceTier: 2,
    durationMin: 60,
    lat: 40.7233,
    lng: -74.0011,
    address: 'Broadway & Prince St, New York, NY',
    description: 'Gallery and shopping walk: cast-iron blocks of art galleries and flagship stores.',
    tags: ['art', 'walk'],
  },
  // ---- Fixed-time daytime events ------------------------------------------
  {
    id: 'evt-film-matinee',
    name: 'Matinee at Film Forum',
    kind: 'event',
    neighborhood: 'SoHo',
    priceTier: 2,
    startTime: '13:30',
    endTime: '15:30',
    lat: 40.7301,
    lng: -74.0048,
    address: '209 W Houston St, New York, NY',
    bookingUrl: 'https://filmforum.org/',
    description: 'Independent movie theater: an afternoon classic-film screening.',
    tags: ['film', 'art'],
  },
  {
    id: 'evt-brooklyn-flea',
    name: 'Brooklyn Flea Market',
    kind: 'activity',
    neighborhood: 'DUMBO',
    priceTier: 1,
    startTime: '10:00',
    endTime: '17:00',
    lat: 40.7033,
    lng: -73.9903,
    address: '80 Pearl St, Brooklyn, NY',
    bookingUrl: 'https://brooklynflea.com/',
    description: 'Outdoor flea market: weekend vintage, records, and local makers under the arches.',
    tags: ['outdoors', 'walk'],
    daysOfWeek: [0, 6],
  },
];

/** Curated NYC seed places (restaurants + bars; flexible timing). */
const CORE_PLACES: Candidate[] = [
  {
    id: 'plc-via-carota',
    name: 'Via Carota',
    kind: 'restaurant',
    neighborhood: 'West Village',
    priceTier: 3,
    durationMin: 90,
    lat: 40.7338,
    lng: -74.0027,
    address: '51 Grove St, New York, NY',
    bookingUrl: 'https://www.viacarota.com/',
    cuisine: 'Italian',
    description: 'Italian trattoria: rustic Village favorite for pasta; no reservations, go early.',
    tags: ['food'],
  },
  {
    id: 'plc-joes-pizza',
    name: "Joe's Pizza",
    kind: 'restaurant',
    neighborhood: 'West Village',
    priceTier: 1,
    durationMin: 30,
    lat: 40.7305,
    lng: -74.0023,
    address: '7 Carmine St, New York, NY',
    bookingUrl: 'https://www.joespizzanyc.com/',
    cuisine: 'Pizza',
    description: 'Classic pizza joint: the benchmark New York slice, eaten standing up.',
    tags: ['food', 'late-night'],
  },
  {
    id: 'plc-katz',
    name: "Katz's Delicatessen",
    kind: 'restaurant',
    neighborhood: 'Lower East Side',
    priceTier: 2,
    durationMin: 60,
    lat: 40.7223,
    lng: -73.9874,
    address: '205 E Houston St, New York, NY',
    bookingUrl: 'https://katzsdelicatessen.com/',
    cuisine: 'Deli',
    description: 'Jewish deli: pastrami on rye at the famous 1888 institution; take a ticket.',
    tags: ['food'],
  },
  {
    id: 'plc-ramen',
    name: 'Ippudo NY',
    kind: 'restaurant',
    neighborhood: 'East Village',
    priceTier: 2,
    durationMin: 60,
    lat: 40.7307,
    lng: -73.9903,
    address: '65 4th Ave, New York, NY',
    bookingUrl: 'https://www.ippudo-us.com/',
    cuisine: 'Japanese',
    description: 'Japanese ramen shop: rich pork-broth noodle bowls; expect a wait.',
    tags: ['food', 'late-night'],
  },
  {
    id: 'plc-slice-1',
    name: 'Artichoke Basille',
    kind: 'restaurant',
    neighborhood: 'East Village',
    priceTier: 1,
    durationMin: 30,
    lat: 40.7322,
    lng: -73.9866,
    address: '321 E 14th St, New York, NY',
    bookingUrl: 'https://www.artichokepizza.com/',
    cuisine: 'Pizza',
    description: 'Late-night pizza counter: the famously heavy artichoke-cream slice.',
    tags: ['food', 'late-night'],
  },
  {
    id: 'plc-attaboy',
    name: 'Attaboy',
    kind: 'bar',
    neighborhood: 'Lower East Side',
    priceTier: 3,
    durationMin: 75,
    lat: 40.7184,
    lng: -73.9916,
    address: '134 Eldridge St, New York, NY',
    bookingUrl: 'https://attaboy.us/',
    description: 'Craft cocktail bar: no menu; bartenders mix to your taste behind an unmarked door.',
    tags: ['bar'],
  },
  {
    id: 'plc-employees-only',
    name: 'Employees Only',
    kind: 'bar',
    neighborhood: 'West Village',
    priceTier: 3,
    durationMin: 75,
    lat: 40.7333,
    lng: -74.0061,
    address: '510 Hudson St, New York, NY',
    bookingUrl: 'https://www.employeesonlynyc.com/',
    description: 'Cocktail bar: speakeasy-style institution with a late-night kitchen.',
    tags: ['bar'],
  },
  {
    id: 'plc-westlight',
    name: 'Westlight',
    kind: 'bar',
    neighborhood: 'Williamsburg',
    priceTier: 3,
    durationMin: 75,
    lat: 40.7223,
    lng: -73.9573,
    address: '111 N 12th St, Brooklyn, NY',
    bookingUrl: 'https://westlightnyc.com/',
    description: 'Rooftop cocktail bar: 22nd floor, with a full sweep of the Manhattan skyline.',
    tags: ['bar', 'rooftop'],
  },
  {
    id: 'plc-llama-inn',
    name: 'Llama Inn',
    kind: 'restaurant',
    neighborhood: 'Williamsburg',
    priceTier: 3,
    durationMin: 90,
    lat: 40.7186,
    lng: -73.9609,
    address: '50 Withers St, Brooklyn, NY',
    bookingUrl: 'https://www.llamainn.com/',
    cuisine: 'Peruvian',
    description: 'Peruvian restaurant: inventive plates; the beef tenderloin skewers are the move.',
    tags: ['food'],
  },
  {
    id: 'plc-lilia',
    name: 'Lilia',
    kind: 'restaurant',
    neighborhood: 'Williamsburg',
    priceTier: 3,
    durationMin: 90,
    lat: 40.7146,
    lng: -73.9563,
    address: '567 Union Ave, Brooklyn, NY',
    bookingUrl: 'https://www.lilianewyork.com/',
    cuisine: 'Italian',
    description: 'Italian restaurant: wood-fired seafood and handmade pasta from Missy Robbins.',
    tags: ['food'],
  },
  {
    id: 'plc-balthazar',
    name: 'Balthazar',
    kind: 'restaurant',
    neighborhood: 'SoHo',
    priceTier: 3,
    durationMin: 90,
    lat: 40.7224,
    lng: -73.9982,
    address: '80 Spring St, New York, NY',
    bookingUrl: 'https://balthazarny.com/',
    cuisine: 'French',
    description: 'French brasserie: grand SoHo classic for steak frites and people-watching.',
    tags: ['food', 'brunch'],
  },
  {
    id: 'plc-time-out',
    name: 'Time Out Market',
    kind: 'restaurant',
    neighborhood: 'DUMBO',
    priceTier: 2,
    durationMin: 60,
    lat: 40.7025,
    lng: -73.9903,
    address: '55 Water St, Brooklyn, NY',
    bookingUrl: 'https://www.timeoutmarket.com/newyork/',
    cuisine: 'Food hall',
    description: 'Food hall: a dozen local restaurant counters, rooftop seating, skyline views.',
    tags: ['food'],
  },
  // ---- Broader neighborhood coverage + daytime brunch/coffee ---------------
  {
    id: 'plc-chelsea-market',
    name: 'Chelsea Market',
    kind: 'restaurant',
    neighborhood: 'Chelsea',
    priceTier: 2,
    durationMin: 60,
    lat: 40.742,
    lng: -74.0061,
    address: '75 9th Ave, New York, NY',
    bookingUrl: 'https://www.chelseamarket.com/',
    cuisine: 'Food hall',
    description: 'Indoor food market: tacos, lobster rolls, and bakeries in the old Nabisco factory.',
    tags: ['food'],
  },
  {
    id: 'plc-jacks-wife-freda',
    name: 'Jack’s Wife Freda',
    kind: 'restaurant',
    neighborhood: 'SoHo',
    priceTier: 2,
    durationMin: 75,
    lat: 40.7228,
    lng: -73.9985,
    address: '224 Lafayette St, New York, NY',
    bookingUrl: 'https://jackswifefreda.com/',
    cuisine: 'Mediterranean',
    description: 'All-day café: Mediterranean comfort food, beloved for brunch shakshuka.',
    tags: ['food', 'brunch'],
  },
  {
    id: 'plc-buvette',
    name: 'Buvette',
    kind: 'restaurant',
    neighborhood: 'West Village',
    priceTier: 2,
    durationMin: 75,
    lat: 40.7333,
    lng: -74.0037,
    address: '42 Grove St, New York, NY',
    bookingUrl: 'https://ilovebuvette.com/',
    cuisine: 'French',
    description: 'French café and wine bar: tiny spot for eggs in the morning, wine at night.',
    tags: ['food', 'brunch'],
  },
  {
    id: 'plc-grimaldis',
    name: 'Grimaldi’s Pizzeria',
    kind: 'restaurant',
    neighborhood: 'DUMBO',
    priceTier: 2,
    durationMin: 60,
    lat: 40.7024,
    lng: -73.9932,
    address: '1 Front St, Brooklyn, NY',
    bookingUrl: 'https://grimaldispizzeria.com/',
    cuisine: 'Pizza',
    description: 'Coal-oven pizzeria: classic whole pies under the Brooklyn Bridge.',
    tags: ['food'],
  },
  {
    id: 'plc-red-rooster',
    name: 'Red Rooster Harlem',
    kind: 'restaurant',
    neighborhood: 'Harlem',
    priceTier: 3,
    durationMin: 90,
    lat: 40.8085,
    lng: -73.9454,
    address: '310 Lenox Ave, New York, NY',
    bookingUrl: 'https://www.redroosterharlem.com/',
    cuisine: 'Southern',
    description: 'Southern comfort-food restaurant: Harlem dining room with live music downstairs.',
    tags: ['food', 'live music'],
  },
  {
    id: 'plc-sylvias',
    name: 'Sylvia’s',
    kind: 'restaurant',
    neighborhood: 'Harlem',
    priceTier: 2,
    durationMin: 75,
    lat: 40.8082,
    lng: -73.9442,
    address: '328 Malcolm X Blvd, New York, NY',
    bookingUrl: 'https://www.sylviasrestaurant.com/',
    cuisine: 'Southern',
    description: 'Soul-food restaurant: Harlem institution since 1962; go for the fried chicken.',
    tags: ['food', 'brunch'],
  },
  {
    id: 'plc-taverna-kyclades',
    name: 'Taverna Kyclades',
    kind: 'restaurant',
    neighborhood: 'Astoria',
    priceTier: 2,
    durationMin: 90,
    lat: 40.7739,
    lng: -73.9109,
    address: '33-07 Ditmars Blvd, Astoria, NY',
    bookingUrl: 'https://www.tavernakyclades.com/',
    cuisine: 'Greek',
    description: 'Greek seafood taverna: Astoria standby; the grilled octopus earns the wait.',
    tags: ['food'],
  },
  {
    id: 'plc-bohemian-hall',
    name: 'Bohemian Hall Beer Garden',
    kind: 'bar',
    neighborhood: 'Astoria',
    priceTier: 2,
    durationMin: 90,
    lat: 40.7702,
    lng: -73.9146,
    address: '29-19 24th Ave, Astoria, NY',
    bookingUrl: 'https://bohemianhall.com/',
    description: 'Czech beer garden: long communal tables under the trees, pouring since 1910.',
    tags: ['bar', 'outdoors'],
  },
  {
    id: 'plc-robertas',
    name: 'Roberta’s',
    kind: 'restaurant',
    neighborhood: 'Bushwick',
    priceTier: 2,
    durationMin: 90,
    lat: 40.705,
    lng: -73.9337,
    address: '261 Moore St, Brooklyn, NY',
    bookingUrl: 'https://www.robertaspizza.com/',
    cuisine: 'Pizza',
    description: 'Wood-fired pizzeria: the Bushwick pioneer with a tiki backyard.',
    tags: ['food'],
  },
  {
    id: 'plc-house-of-yes',
    name: 'House of Yes',
    kind: 'bar',
    neighborhood: 'Bushwick',
    priceTier: 2,
    durationMin: 90,
    lat: 40.7069,
    lng: -73.9233,
    address: '2 Wyckoff Ave, Brooklyn, NY',
    bookingUrl: 'https://houseofyes.org/',
    description: 'Nightclub and performance venue: circus-themed warehouse with aerialists.',
    tags: ['bar', 'live music'],
  },
  {
    id: 'plc-paulie-gees',
    name: 'Paulie Gee’s',
    kind: 'restaurant',
    neighborhood: 'Greenpoint',
    priceTier: 2,
    durationMin: 75,
    lat: 40.7296,
    lng: -73.9585,
    address: '60 Greenpoint Ave, Brooklyn, NY',
    bookingUrl: 'https://pauliegee.com/',
    cuisine: 'Pizza',
    description: 'Wood-fired pizzeria: Greenpoint den famous for the hot-honey Hellboy pie.',
    tags: ['food'],
  },
  {
    id: 'plc-peter-pan',
    name: 'Peter Pan Donut & Pastry',
    kind: 'restaurant',
    neighborhood: 'Greenpoint',
    priceTier: 1,
    durationMin: 30,
    lat: 40.7241,
    lng: -73.9509,
    address: '727 Manhattan Ave, Brooklyn, NY',
    bookingUrl: 'https://peterpandonuts.com/',
    cuisine: 'Bakery',
    description: 'Old-school donut shop: Greenpoint counter classic; get the red velvet early.',
    tags: ['food', 'coffee'],
  },
  {
    id: 'plc-abraco',
    name: 'Abraço Coffee',
    kind: 'restaurant',
    neighborhood: 'East Village',
    priceTier: 1,
    durationMin: 30,
    lat: 40.7273,
    lng: -73.9852,
    address: '81 E 7th St, New York, NY',
    cuisine: 'Coffee',
    description: 'Espresso bar: tiny standing-room counter for coffee and olive-oil cake.',
    tags: ['food', 'coffee'],
  },
  {
    id: 'plc-joe-coffee-wv',
    name: 'Joe Coffee Company',
    kind: 'restaurant',
    neighborhood: 'West Village',
    priceTier: 1,
    durationMin: 30,
    lat: 40.7346,
    lng: -74.0025,
    address: '141 Waverly Pl, New York, NY',
    bookingUrl: 'https://joecoffeecompany.com/pages/west-village',
    cuisine: 'Coffee',
    description: 'Neighborhood coffee shop: corner counter on Waverly Place, a Village original since 2003.',
    tags: ['food', 'coffee'],
  },
  {
    id: 'plc-ludlow-coffee',
    name: 'Ludlow Coffee Supply',
    kind: 'restaurant',
    neighborhood: 'Lower East Side',
    priceTier: 1,
    durationMin: 30,
    lat: 40.7207,
    lng: -73.9878,
    address: '176 Ludlow St, New York, NY',
    bookingUrl: 'https://ludlowcoffeesupply.com/',
    cuisine: 'Coffee',
    description: 'LES coffee shop: big communal tables and a solid espresso menu on Ludlow St.',
    tags: ['food', 'coffee'],
  },
  {
    id: 'plc-devocion-wburg',
    name: 'Devoción',
    kind: 'restaurant',
    neighborhood: 'Williamsburg',
    priceTier: 2,
    durationMin: 30,
    lat: 40.7139,
    lng: -73.9573,
    address: '148 Grand St, Brooklyn, NY',
    bookingUrl: 'https://www.devocion.com/',
    cuisine: 'Coffee',
    description: 'Coffee roastery and café: greenhouse-like space serving Colombian beans roasted on-site.',
    tags: ['food', 'coffee'],
  },
];

/** The full pools the providers serve: hand-picked core + generated catalog. */
export const SEED_EVENTS: Candidate[] = [...CORE_EVENTS, ...CATALOG_EVENTS];
export const SEED_PLACES: Candidate[] = [...CORE_PLACES, ...CATALOG_PLACES];

/** Storage namespace prefix. */
export const STORAGE_PREFIX = 'outnyc:v1:';
